### ISSUE TITLE
Clicking on text disables proxy

### ISSUE THREAD

**Issue by selenamarie** [mozilla/secure-proxy#183]
I clicked on the text in the attached image and it disabled (and the "disabled" message is clickable to re-enable) the proxy. That was surprising to me!

<img width="321" alt="Screen Shot 2019-07-18 at 3 02 11 PM" src="https://user-images.githubusercontent.com/54803/61495227-32c7e000-a96d-11e9-90f0-f566296e7327.png">

My expectation was that clicking on the text /would not/ disable or enable the proxy.

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible using the latest Secure Proxy add-on (v0.13), with the latest Firefox Release (70.0), Beta (71.0b3) and Nightly (72.0a1). Verified on Windows 10 x64, Mac 10.14.2 and Linux Ubuntu 16.04 x64.
