### ISSUE TITLE
On IPv6-only network stuck in endless connection state

### ISSUE THREAD

**Issue by nils-ohlmeier** [mozilla/secure-proxy#237]
I tried to turn on SP on a IPv6 only network at IETF and it results in the following state:
<img width="324" alt="Screen Shot 2019-07-24 at 13 36 01" src="https://user-images.githubusercontent.com/6109500/61819673-829d2000-ae21-11e9-83de-390e4b929105.png">

I then manually tried to switch SP off, which resulted in this:
<img width="314" alt="Screen Shot 2019-07-24 at 13 36 25" src="https://user-images.githubusercontent.com/6109500/61819729-99437700-ae21-11e9-99d4-32ff00eeef9b.png">

But as soon as I would close and re-open the dialog window I would see the first screen shot again.

In fact when I switched back to the IPv4 network SP would then connect, even though I had tried to turn it off.

**Comment by miyurusankalpa** [comment]
@bakulf Still does not work.

I saw 2 main issues going through the code.

1. **firefox.factor11.cloudflareclient.com** is IPv4 only, it does not return a IPv6 address. Maybe Cloudflare WARP back-end does not support IPv6 tunneling yet.

2.  On the DoH configuration IPv4 address is hard corded,  no IPv6 address present.
https://github.com/mozilla/secure-proxy/blob/ef8a7ac0bbae9bb22e6c44520ca079d28f77dca9/src/background/network.js#L5

**Comment by aplunk** [comment]
@bakulf I was unaware of this issue. Adding IPv6 support to the proxy shouldn't be a problem. Please assign this or a linked ticket to me to track ipv6 support.

**Comment by bakulf** [comment]
Fixed
