### ISSUE TITLE
Verify content in about:addons

### ISSUE THREAD

**Issue by pdehaan** [mozilla/secure-proxy#273]
This is from the signed v0.4 build (in Nightly).
Just want to confirm that everybody is happy with the current details:

| NAME | VALUE |
|:-----|:------|
| `name` | "Firefox Private Network"
| `description` | "A secure, encrypted tunnel to the web to protect yourself everywhere you use Firefox."
| `author` | "Firefox"
| `icon` |

![Add-ons_Manager](https://user-images.githubusercontent.com/557895/62092883-e2356a00-b22b-11e9-9138-68eb4940215f.png)

/cc @arthur-mozilla

**Comment by bakulf** [comment]
I guess we are happy with these values.
