### ISSUE TITLE
0.6 blocks appear.in usage even in off state

### ISSUE THREAD

**Issue by nils-ohlmeier** [mozilla/secure-proxy#322]
With the 0.5 version of the extension installed, but NOT turned on, I can no longer use appear.in.

Trying to enter a meeting room like e.g. https://appear.in/secureproxytest results only in an empty page. On the console the following errors get logged:
`TypeError: "prototype" is read-only
main.8f8d51b0.js:13:547010
Error: [$injector:unpr] http://errors.angularjs.org/1.5.8/$injector/unpr?p0=redirectServiceProvider%20%3C-%20redirectService angular.js:38
`

Blocking WebRTC PeerConnection when the SP is turned on is expected. But it should not prevent me from using WebRTC when SP is off.

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible with the latest Secure Proxy add-on (v0.13), using the latest Firefox Release (70.0), Beta (71.0b3) and Nightly (72.0a1). Verified on Windows 10 x64, Mac 10.14.2 and Linux Ubuntu 16.04 x64.
