### ISSUE TITLE
GuM is not working with Secure Proxy off

### ISSUE THREAD

**Issue by SoftVision-LorandJanos** [mozilla/secure-proxy#353]
#### Affected versions:
- All Firefox versions.

#### Affected Platforms:
- All Windows

#### Prerequisites:
Secure Proxy is installed and disabled.

#### Steps to reproduce
1. Go to [GuM Test Page](https://mozilla.github.io/webrtc-landing/gum_test.html).
2. Click on "Audio & Video".

#### Expected result:
A prompt for permissions to access the camera and microphone on your machine is displayed.

#### Actual result:
- The prompt is not displayed.
- The "NotAllowedError: The request is not allowed by the user agent or the platform in the current context." message is displayed.

![Screenshot (156)](https://user-images.githubusercontent.com/48829350/62710257-a9ea1480-b9ff-11e9-92d3-c74257ad7110.png)

**Comment by bsurd** [comment]
Verified in v11 and the issue is no longer reproducible.
