### ISSUE TITLE
Revoking Firefox Private Network in accounts.firefox.com doesn't seem to have any visible effect on the extension

### ISSUE THREAD

**Issue by pdehaan** [mozilla/secure-proxy#356]
Via [Slack](https://mozilla.slack.com/archives/CM2Q7BVHA/p1565304136030100):

> **Grisha Kruglov 3:42 PM**: Revoking Firefox Private Network in accounts.firefox.com doesn't seem to have any visible effect on the extension. After revoking, i can still toggle it on/off, and its settings don't indicate that there's any problem with the account.
> After being revoked, Firefox Private Network seems to have re-appeared in the list of devices and apps. After initial revoke, i've restarted Firefox (nightly update), and toggled private network on/off a few times.
> After revoked it the second time, it doesn't seem to re-appear in the list. However, extension is still seemingly unaffected.

> **Ryan Kelly  15 minutes ago** That this doesnt immediately disconnect the proxy is expected (cached access tokens valid for several hours) but the reappearing-after-revoke sounds like an FxA-side bug; it would be interesting to repro with a non-secret client e.g. Notes

> ...

**Comment by bakulf** [comment]
See #391
