### ISSUE TITLE
Tighten up the WebRTC modal dialog UX

### ISSUE THREAD

**Issue by pdehaan** [mozilla/secure-proxy#358]
Via [Slack](https://mozilla.slack.com/archives/CHN4GSYJE/p1565309108362500):

> **[Martin Thomson 5:05 PM]:** Gotta say, that WebRTC modal dialog is pretty poor UX.  Does it need to be so intrusive?
> The message is nice and clear.  But I was visiting the https://appear.in homepage.  There was no WebRTC on that page, just information about WebRTC services.

**Comment by bakulf** [comment]
WebRTC blocking has been removed in v18. This bug is now invalid.
