### ISSUE TITLE
WebRTC seems to be blocked, but there's no warning about that or UI when it happens

### ISSUE THREAD

**Issue by pdehaan** [mozilla/secure-proxy#360]
Via [Slack](https://mozilla.slack.com/archives/CM2Q7BVHA/p1565308683063000):

> **[Jed Davis 4:58 PM]:** WebRTC seems to be blocked (by interposing the DOM APIs and throwing exceptions), but there's no warning about that or UI when it happens.

**Comment by bakulf** [comment]
WebRTC blocking has been removed in v18. This bug is now invalid.
