### ISSUE TITLE
REQ: the on/off setting be container specific

### ISSUE THREAD

**Issue by pdehaan** [mozilla/secure-proxy#362]
Via [Slack](https://mozilla.slack.com/archives/CM2Q7BVHA/p1565309259070500):

> **[Julien Vehent 5:07 PM]:** FEATURE REQUEST: the on/off setting be container specific. that'd be a killer feature!

/cc @moz-jvehent

**Comment by bakulf** [comment]
We support proxy passthrough pref. This can be set in about:preferences.
