### ISSUE TITLE
Getting "Unexpected error" from FxA server

### ISSUE THREAD

**Issue by pdehaan** [mozilla/secure-proxy#393]
This has been reported twice now (once for Ubuntu Nightly, and one for a Windows Nightly). @rfk hinted this might be an FxA issue, but just wanted to make sure we were tracking this somehow. Feel free to migrate this issue over to **mozilla/fxa** if we think it belongs there instead.

The second report (David Lawrence/Windows 10) reported that it worked for him after switching to a new profile (which might be a thing, or maybe was just coincidental timing issues).

---

Via [Slack](https://mozilla.slack.com/archives/CM2Q7BVHA/p1565319112089500):

> **[Colin Lee 7:51 PM]:** I seem to be getting sign-in errors on Linux Nightly on Ubuntu 18.04. This is before I've even been given the option to enter any password.

![Screenshot from 2019-08-08 21-48-25](https://user-images.githubusercontent.com/557895/62800620-abb3e680-ba98-11e9-8d99-dd5bbb849926.png)

> **[Ryan Kelly  14 hours ago]:** This seems likely to be an error in fxa, anything in dev console output?

> **[Colin Lee  6 hours ago]:** Lots of stuff.
> ![Screenshot from 2019-08-09 07-35-48](https://user-images.githubusercontent.com/557895/62800708-e027a280-ba98-11e9-9886-e5c6d45db24e.png)
> FWIW, I'm signed into fxa for other things like sync.

---

Via [Slack](https://mozilla.slack.com/archives/CM2Q7BVHA/p1565372279231400):

> **[David Lawrence 10:37 AM]:** Has it been asked already about getting 'Unexpected error" when trying to sign in with my firefox account?
> i get the error right after clicking sign in. Consistently on nightly/windows
>
> i suppose i could try with a new profile as well and see if it still occurs
>
> ok it works with a fresh profile

**Comment by bakulf** [comment]
Fixed
