### ISSUE TITLE
Unable to connect to proxy when public network requires clicking "I accept" button

### ISSUE THREAD

**Issue by pdehaan** [mozilla/secure-proxy#397]
Via [Slack](https://mozilla.slack.com/archives/CM2Q7BVHA/p1565377728249500):

> **[sstangl 12:08 PM]:** Bug: I'm trying it from an actual public wifi location (university campus) -- it doesn't seem to work. When Firefox starts it says "... Needs Your Attention," and it's off. When I go to sign in, I pass the sign-in dialog, but nothing happens -- it pops up again "Needs Your Attention," and the GUI shows that it's "Off." But when I go to access a website, it complains that the proxy server is refusing connections. I can only get out of this state by restarting Firefox.
> I can record this, actually! One second.

> **[[sstangl 12:12 PM]](https://mozilla.slack.com/archives/CM2Q7BVHA/p1565377925252900):** Here's a screencast showing trying to sign in from public wifi (and it failing silently). At the end, the video cuts out, but the screen turns into "Proxy server is refusing connections."

> **[sstangl  25 minutes ago]:** The public network requires clicking an "I Accept" button on a landing page before it allows proceeding.

(Video is a .webm -- I can't seem to embed it here, but you can see it in Slack at https://mozilla.slack.com/archives/CM2Q7BVHA/p1565377925252900)

**Comment by bakulf** [comment]
This is fixed in the latest versions.
