### ISSUE TITLE
New copy for WebRTC modal and extension panel 

### ISSUE THREAD

**Issue by betsymi** [mozilla/secure-proxy#412]
Revised copy for the modal and the extension for our tab implementation of WebRTC.
### **Modal on sites with WebRTC (hangouts, meet.google, messenger.com, appear.in, jitsi.org, talky.io, webex.com, etc.)**

> To protect your connection to website.com, Private Network disabled parts of this page. Turning off Private Network will enable all functionality, but makes your connection to sites in this tab less secure.
> 
> [ Keep On ] [ Turn Off in This Tab ]

 Please  note both CTAs on the modal are different. 

### **Copy in extension panel once FPN is turned off**

> This tab is not protected by the Private Network proxy service. Your location is visible to ad trackers and websites you visit in this tab.
>
> Private Network is not currently compatible with some sites that use live audio, video, or chats. `Learn more`

Learn more link will go to a SUMO page. I will get the link.

**Comment by bakulf** [comment]
WebRTC blocking has been removed in v18. This bug is now invalid.
