### ISSUE TITLE
Using miro.com in Nightly with Private Network it seems to have a lot of trouble and has to "disconnect"/"reconnect" [v0.6]

### ISSUE THREAD

**Issue by pdehaan** [mozilla/secure-proxy#442]
Via [Slack](https://mozilla.slack.com/archives/CM2Q7BVHA/p1565897097426000):

Using v0.6...

> **[Nicole Shadowen (she/her) 12:24 PM]:** Hi all! Thank you for the excellent work on Private Network, I've been really excited to try it out in Nightly. One bit of feedback - our team uses Miro boards (used to be called Realtimeboard) pretty consistently for our work. However, when I go to use Miro in Nightly with Private Network it seems to have a lot of trouble and has to "disconnect"/"reconnect" so much that I can't use Miro with Private Network on.

> **[Nicole Shadowen (she/her)  2 hours ago]:** I looked into the issue a bit and found this if it's helpful: https://help.miro.com/hc/en-us/articles/360017572694-Connection-Could-Not-Be-Established (edited)

> **[Nicole Shadowen (she/her)  2 hours ago]:**
actually I just realized my private network switched off for some reason. I switched it on and now it appears miro is working regularly now.. will update if any of these issues seem to persist

**Comment by bakulf** [comment]
Fixed in v17.
