### ISSUE TITLE
Wrong window brought forward to show a doorhanger notification [v0.6]

### ISSUE THREAD

**Issue by pdehaan** [mozilla/secure-proxy#443]
Via [Slack](https://mozilla.slack.com/archives/CM2Q7BVHA/p1565899807428300

> **[Rob Helmer 1:10 PM]:** Hm. I just re-enabled PN, and it brought the wrong window forward to show a doorhanger notification.

> **[Rob Helmer  2 hours ago]:** Is that using the standard WebExtension `browserAction`? If so it's probably a bug in Firefox WE I guess

**Comment by bakulf** [comment]
Dup of #509
