### ISSUE TITLE
The proxy server is refusing connections [v0.6]

### ISSUE THREAD

**Issue by pdehaan** [mozilla/secure-proxy#469]
Via [Slack](https://mozilla.slack.com/archives/CM2Q7BVHA/p1566241344475200),

**[Keith Willowhawk:small_airplane: 12:02 PM]:** Experience while traveling was interesting.  Hopping on free airport wifi (with a fast follow of enabling my VPN) yielded it working fine and then while in session it broke, and required reauthentication, and all sorts of wonkiness happened.  In thread I’ll post screen shots etc.

**[Keith Willowhawk:small_airplane:  3 hours ago]:** I was clicking a link on my [bank’s site](https://barclaycardus.com) (public WiFi, NordVPN, Nightly, FPN on) and everything was fine until this…

![CleanShot 2019-08-17 at 17 42 58](https://user-images.githubusercontent.com/557895/63302778-dff68680-c292-11e9-90e6-f54ada78774d.png)

**[Keith Willowhawk:small_airplane:  3 hours ago]:** WiFi seemed stable, no issues with VPN, but FPN puked.

![CleanShot 2019-08-17 at 17 40 24](https://user-images.githubusercontent.com/557895/63302862-16cc9c80-c293-11e9-89fc-31dc5725c85e.png)

![CleanShot 2019-08-17 at 17 40 08](https://user-images.githubusercontent.com/557895/63302896-28ae3f80-c293-11e9-9b84-de1c214d46bc.png)

**[Keith Willowhawk:small_airplane:  3 hours ago]:** Not sure if this helps…

![CleanShot 2019-08-17 at 17 39 51](https://user-images.githubusercontent.com/557895/63302927-3ebc0000-c293-11e9-8dfe-e797e40d2eab.png)

**Comment by bakulf** [comment]
Fixed in v17.
