### ISSUE TITLE
Button labels on the modal are confusing

### ISSUE THREAD

**Issue by pdehaan** [mozilla/secure-proxy#486]
Ref #428

Via [Slack](https://mozilla.slack.com/archives/CM2Q7BVHA/p1566333172010400),

**Hal Wine Today at 1:32 PM**
fwiw, I found the button legends on the attached screen shot confusing:

<img width="579" alt="Slack___private-network-alpha___Mozilla" src="https://user-images.githubusercontent.com/557895/63382852-776ddf00-c350-11e9-9d30-53c77d3e3f11.png">

**Hal Wine  7 minutes ago**
What does "not now" mean?
- right now, leave my connection alone and show everything?
- right now, disable those parts, but only for this session?
-  right now, leave those parts disabled?

**Hal Wine  5 minutes ago**
Similarly, "turn off for this tab" is confusing. I'm used to configuring tracking protections by site, not tab. Does it really mean tab? What happens if I duplicate the tab? Do the setting follow?

**Hal Wine  4 minutes ago**
And am I "turning off" the extra layer of protection? Or "turning off" the suspect elements?

/cc @betsymi @brassy-

**Comment by bakulf** [comment]
The webRTC dialog has been removed.
