### ISSUE TITLE
Site worked fine then stopped loading [v0.6]

### ISSUE THREAD

**Issue by pdehaan** [mozilla/secure-proxy#488]
Via [Slack](https://mozilla.slack.com/archives/CM2Q7BVHA/p1566337476016200),

**Hal Wine Today at 2:44 PM**
Interesting case FPN with Nightly on win10. I was browsing startech.com fine (if sluggish), then it stopped loading. Now only works with FPN off, and always fails with FPN on.
Deeper URL: https://www.startech.com/Server-Management/KVM-Switches/Portable-USB-PS-2-KVM-Console-Adapter-for-Notebook-PCs~NOTECONS01

**Hal Wine  1 hour ago**
To repro on a clean profile, I'd need to set up a new FxA account. I tried, and as soon as I logged in, FxA helpfully sync'd all settings & extensions. /o\

**Comment by bakulf** [comment]
This has been fixed by Cloudflare recently.
