### ISSUE TITLE
Proxy disconnected due to FxA auth issue [v0.6]

### ISSUE THREAD

**Issue by pdehaan** [mozilla/secure-proxy#508]
Via [Slack](https://mozilla.slack.com/archives/CM2Q7BVHA/p1566427542045900),

**Benson Wong 3:45 PM**
proxy disconnected due to fxa auth issue again.  Clicked on the sign in button and this window popped up and hung there.  Had to restart the browser (nightly) in order to get it unstuck.
guess:
- all web requests didn't work when PN disconnected/failed (weird state?)
- trying to go to accounts.firefox.com didn't work cause of PN failure(?)
- result: stuck. (edited) 

<img width="389" alt="Slack___private-network-alpha___Mozilla___1_new_item" src="https://user-images.githubusercontent.com/557895/63541818-c001d580-c4d3-11e9-8372-1f79e4604dc8.png">

/cc @rfk

**Comment by bakulf** [comment]
Fixed
