### ISSUE TITLE
Error messages that Firefox is configured to use a proxy server that's refusing connections [v0.6]

### ISSUE THREAD

**Issue by pdehaan** [mozilla/secure-proxy#510]
Via [Slack](https://mozilla.slack.com/archives/CM2Q7BVHA/p1566486162052700),

**Jed Davis 8:02 AM**
Seems to be broken with captive portals — I get error messages that Firefox is configured to use a proxy server that's refusing connections.

**Jed Davis [8:03 AM](https://mozilla.slack.com/archives/CM2Q7BVHA/p1566486229054000)**
(The Denver “office”, a room in a coworking space, has some Meraki nonsense with a captive portal that doesn't always go away after you authenticate.)

**Nhi Nguyen  1 hour ago**
can you turn networking logging on (about:networking) and try to reproduce please?

**Nhi Nguyen  1 hour ago**
cc @mayhemer

**Comment by bakulf** [comment]
This should be fixed in v17.
