### ISSUE TITLE
WebRTC dialog doesn't give enough information to make a decision [v0.6]

### ISSUE THREAD

**Issue by pdehaan** [mozilla/secure-proxy#527]
Via @mostlygeek in [Slack](https://mozilla.slack.com/archives/CM2Q7BVHA/p1566840413086700),

**Benson Wong 10:26 AM**
This message doesn't give me enough information to make a decision I think.  I would like to know what was disabled

![278F9208-63B6-4DBD-A322-36173266FFD9](https://user-images.githubusercontent.com/557895/63712451-9954df00-c7f2-11e9-8597-6e6d1bc8714c.jpg)

**Benson Wong  1 hour ago**
I turned it off and the result definitely didn't meet expectations :smile:

![AAEB4839-F03C-44B4-BFFF-EA2C1A9C0943](https://user-images.githubusercontent.com/557895/63712493-b38ebd00-c7f2-11e9-872f-de987d245ef1.jpg)

**Alice Rhee  1 hour ago**
Follow up Q:  how would knowing that info influence your decision? (edited)

**Comment by bakulf** [comment]
WebRTC blocking has been removed in v18. This bug is now invalid.
