### ISSUE TITLE
Potential IP address leak when Firefox reloads and before proxy connects [v0.8]

### ISSUE THREAD

**Issue by pdehaan** [mozilla/secure-proxy#543]
Via [Slack](https://mozilla.slack.com/archives/CM2Q7BVHA/p1566908613114200),

**David Heiberg 5:23 AM**
When updating nightly, it reloads the browser and reloads the tab you are currently on. This can cause your IP address to leak since the tab is loading before FPN connects. I'm not sure what the best way to reproduce this is other than waiting for a new nightly and having the current tab be open on an IP checking website.

**Comment by bakulf** [comment]
Fixed.
