### ISSUE TITLE
Problems logging into usbank.com with proxy enabled [v0.6]

### ISSUE THREAD

**Issue by pdehaan** [mozilla/secure-proxy#544]
via [Slack](https://mozilla.slack.com/archives/CM2Q7BVHA/p1566953675132000),

**Keith Willowhawk 5:54 PM**
Another bank site with wonky login…FPN on, produces an error that the site is unavailable.  FPN off, works fine.  For extra validation I disabled all Plugins and Add-ons except FPN and retried.  Same result.  Logs and screenshot in threads.

![CleanShot 2019-08-27 at 18 51 52](https://user-images.githubusercontent.com/557895/63899579-3c078c00-c9b2-11e9-93a8-fafe64ea4db0.png)

[console-export-2019-8-27_18-49-57_alldisabled_FPNon.txt](https://github.com/mozilla/secure-proxy/files/3553234/console-export-2019-8-27_18-49-57_alldisabled_FPNon.txt)

[console-export-2019-8-27_18-43-34_alldisabled_noFPN.txt](https://github.com/mozilla/secure-proxy/files/3553236/console-export-2019-8-27_18-43-34_alldisabled_noFPN.txt)

**Comment by bakulf** [comment]
Fixed
