### ISSUE TITLE
QR code scanning to sign into sync on FPN doesn't work [v0.6]

### ISSUE THREAD

**Issue by pdehaan** [mozilla/secure-proxy#545]
Via [Slack](https://mozilla.slack.com/archives/CM2Q7BVHA/p1566942500129300),

**Jonathan Almeida 2:48 PM**
QR code scanning to sign into sync on FPN doesn't work - forever loading wheel.

**Vlad Filippov  1 day ago**
interesting!
oh it connects to websockets, maybe that's why?

**Peter deHaan  6 minutes ago**
@vladikoff Are you tracking this on the FxA side, or should I file a secure-proxy issue?

**Vlad Filippov  5 minutes ago**
@pdehaan file an issue on the secure proxy

**Comment by bakulf** [comment]
Fixed.
