### ISSUE TITLE
FPN does not turn on properly

### ISSUE THREAD

**Issue by bsurd** [mozilla/secure-proxy#552]
#### Affected versions:
- Firefox Nightly 70.0a1.
- Firefox Beta 69.0b16.
- Firefox Release 68.0.2.

#### Affected Platforms:
- Windows 10 (64-bit)
- MacOS 10.14.5
- Linux Ubuntu 19.04 (64-bit)
- Linux Mint 19.1 Cinnamon (64-bit)

#### Steps to reproduce
1. Go to [Messenger](https://www.messenger.com/).
2. While the page is loading open the FPN doorhanger.
3. Turn off FPN.
4. From the modal that was displayed select "Turn Off in This Tab".
5. On the same page or after browsing to a different page in the same tab turn on FPN.

#### Expected result:
FPN is turned on.

#### Actual result:
FPN remains turned off with with the UI being changed as if you've just turned it off from the modal. 

![e3qwe21d1](https://user-images.githubusercontent.com/17178945/63939956-22794980-ca71-11e9-9575-5fa1fdf59cb7.gif)

**Comment by bakulf** [comment]
I think we can ignore these webRTC issues because the dialog is going to be removed soon.

**Comment by bsurd** [comment]
Closing based on https://github.com/mozilla/secure-proxy/issues/552#issuecomment-552896817 .
