### ISSUE TITLE
After FPN prompts me to disable it for a tab, I get a notification popping down from the FPN toolbar icon each time I visit that tab [v0.8]

### ISSUE THREAD

**Issue by pdehaan** [mozilla/secure-proxy#559]
Via **Daniel Holbert** in [Slack](https://mozilla.slack.com/archives/CM2Q7BVHA/p1567116606030000),

**Daniel Holbert 3:10 PM**
Bug report, new for 0.8: after FPN prompts me to disable it for a tab (which I agree to), then each time I visit that tab, I get a prominent `Firefox Private Network needs your attention!` notification popping down from the FPN toolbar icon (edited) 

Testcase which uses WebRTC (which seems to be what triggers the disable-for-this-tab prompt): https://webrtc.github.io/samples/src/content/getusermedia/gum/

Screenshot (the yellow notification appears **each time I visit this tab**, even after I've clicked the icon or elsewhere in an attempt to make the notification stop):

![image (4)](https://user-images.githubusercontent.com/557895/63982925-58223080-ca79-11e9-8671-62018b9a1bef.png)

I hit this in my main browsing profile, and also repro'd in a basically-fresh profile (with very little browisng history, and FPN is the only extension; I did have version 0.6 previously installed in case that matters, though this is now with version 0.8.)

**Jonathan Kingston  1 hour ago**
This was intentional. I think the rationale is to warn the user of the risk.

**Daniel Holbert  1 hour ago**
...every time they switch to the tab?
this feels super-annoying/spammy FWIW
particularly for frequently-visited tabs like https://web.whatsapp.com/ (my phone's whatsapp chats mirrored to my computer), which is a tab I visit ~frequently (edited)

Makes sense to prompt before disabling (which we do) and notify with a visual indicator (which we do), and perhaps even to pop up a dialog once per tab as a reminder. But every time you visit the tab seems overly aggressive

(Also, the dialog is devoid of information right now -- it just says the addon "needs your attention", which isn't especially helpful if we're really trying to convey risk)

(Sorry for bluntness; I do love the add-on in general.)

**Comment by bakulf** [comment]
WebRTC blocking has been removed in v18. This bug is now invalid.
