### ISSUE TITLE
Firefox crashes when using send with FPN to send archives

### ISSUE THREAD

**Issue by bsurd** [mozilla/secure-proxy#561]
#### Affected versions:
- Firefox Nightly 70.0a1.
- Firefox Beta 69.0b16.
- Firefox Release 69.

#### Affected Platforms:
- Windows 10 (64-bit)
- Mac 10.14.5

#### Prerequisites
FPN is installed and enabled.

#### Steps to reproduce
1. Go to [Send](http://send.firefox.com) meeting room.
2. Upload any archived file.

#### Expected result:
The file uploads without any issues.

#### Actual result:
Firefox crashes.

#### Notes:
If turning FPN off the file uploads without any issues. Other types of files did not seem to be affected.
[Crash Report](https://crash-stats.mozilla.org/report/index/8a3a7180-c5ff-4df6-953b-2c6f90190830)

![2](https://user-images.githubusercontent.com/17178945/64020820-34bfba00-cb3b-11e9-9cf5-8362bab71b0d.gif)

**Comment by bakulf** [comment]
Fixed in 69.0.1

**Comment by bsurd** [comment]
This issue has been verified using v11 of Secure Proxy, no other issues have been encountered while testing this.
