### ISSUE TITLE
FPN Not working after coming back online

### ISSUE THREAD

**Issue by pdehaan** [mozilla/secure-proxy#569]
Ref #385 

Via https://github.com/mozilla-services/private-network/issues/104

> Utilizing v0.8 I've returned to my computer after it being asleep for the night and FPN doesn't work, when i disconnect and then reconnect I get an error. After a few hours, I'm able to connect without the errors.
>
> Please see issue here: https://drive.google.com/open?id=1wOIaUoW4acYx6R2d8KwNROCIOjNG7Kh1

/cc @tcinotto

**Comment by lime124** [comment]
this is kind of similar. i wake up my computer from the night and FPN is cycling between on, off, and 'needs my attention'. It won't stop and I can't turn it off. 

I have a video I made with quicktime that i can't seem to attach - IDK how to make animated gifs :( I'm @tif on slack.

**Comment by mayhemer** [comment]
@lime124 Can you please [capture logs](https://developer.mozilla.org/en-US/docs/Mozilla/Debugging/HTTP_logging) if you still can reproduce?  Thanks.

**Comment by lime124** [comment]
@mayhemer sorry i have no idea how to do that.

**Comment by mayhemer** [comment]
@lime124 please just follow these instructions: https://developer.mozilla.org/en-US/docs/Mozilla/Debugging/HTTP_logging#Using_aboutnetworking

**Comment by stpeter** [comment]
I had the same experience as @lime124 and I've sent logs directly to @bakulf - will see if I can duplicated it again the next time my computer wakes up from sleep.

**Comment by pdehaan** [comment]
There are some more details/GIFs in the Slack thread: https://mozilla.slack.com/archives/CM2Q7BVHA/p1568217692147200 and https://mozilla.slack.com/archives/CM2Q7BVHA/p1568217897148400?thread_ts=1568217864.148300&cid=CM2Q7BVHA

**Comment by bakulf** [comment]
This has been fixed in the last PRs.
