### ISSUE TITLE
The "Arrow" pointer is wrongly changed into the "text caret" one if the button labels from the "WEB RTC" modal are hovered

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/secure-proxy#571]
**[Affected versions]:**
- Firefox Release 68.0.2 - Build ID: 20190813150448
- Firefox Beta 69.0 - Build ID: 20190827005903
- Firefox Nightly 71.0a1 - Build ID: 20190902094857

**[Affected Platforms]:**
- All Windows
- All Linux
- All Mac

**[Prerequisites]:**
- Have a new Firefox profile with the latest version (0.8) of the "Firefox Private Network" add-on installed.
- You are logged in to "Secure Proxy".
- The browser location is set to "US".
	
**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to the "https://www.messenger.com/" website.
3. Hover the button's labels and observe the behavior.

**[Expected result]:**
- The buttons are highlighted with dark grey.

**[Actual result]:**
- The buttons are highlighted and the "Arrow" pointer is changed into the "Text Caret" one.

**[Notes]:**
- This issue is reproducible on all the websites where the "WEB RTC" modal is displayed.
- This issue is not reproducible with the "non-US" modal from the "landing" page.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/64121462-908e7b00-cda7-11e9-98f4-c7f4909d83f8.gif)

**Comment by bakulf** [comment]
WebRTC blocking has been removed in v18. This bug is now invalid.

**Comment by SoftVision-LorandJanos** [comment]
Marking this bug as Wontfix issue.
