### ISSUE TITLE
Middle click on any link from Settings opens SP doorhanger in new tab

### ISSUE THREAD

**Issue by SoftVision-LorandJanos** [mozilla/secure-proxy#577]
#### Affected versions:
- Firefox Nightly 70.0.a1
- Firefox Beta 69.0b16.
- Firefox Release 68.0.2.

#### Affected Platforms:
- Windows 10 (64-bit).
- MacOS 10.14.5.
- Linux Mint 19.1 Cinnamon.

#### Prerequisites:
The user is logged in to Secure Proxy.

#### Steps to reproduce
1. Display the Secure Proxy doorhanger.
2. Click on the "Settings" button.
3. Open any link from the Settings menu in a new tab, using the middle click.

#### Expected result:
The corresponding link opens in a new tab.

#### Actual result:
A semi-functional Secure Proxy doorhanger is displayed in a new tab for every link.

#### Notes:
The same result happens when using the "Right click>Open in new tab" command for every link in the Settings menu.

![g](https://user-images.githubusercontent.com/48829350/64159430-e95f2180-ce42-11e9-8b07-ffadc8c6daad.gif)

**Comment by bakulf** [comment]
This is fix and verifiable in v10. Closing the bug.

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Private Network" add-on (v10 from 09/16/2019) installed, on the latest Firefox Nightly (71.0a1 Build ID - 20190916093313). Verified on Windows 10 x64, Mac 10.14.6 and Arch Linux 4.16.6 x64.
