### ISSUE TITLE
The modals cannot be dismissed using the "Esc" key

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/secure-proxy#582]
**[Affected versions]:**
- Firefox Release 68.0.2 - Build ID: 20190813150448
- Firefox Beta 69.0 - Build ID: 20190827005903
- Firefox Nightly 71.0a1 - Build ID: 20190903094847

**[Affected Platforms]:**
- All Windows
- All Linux
- All Mac

**[Prerequisites]:**
- Have a new Firefox profile with the latest version (0.8) of the "Firefox Private Network" add-on installed.
- You are logged in to "Secure Proxy".
- The browser location is set to "US".
	
**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to the "https://www.messenger.com/" website.
3. Press the "Esc" key and observe the behavior.

**[Expected result]:**
- The modal is dismissed.

**[Actual result]:**
- Nothing happens.

**[Notes]:**
- This issue is also reproducible with the "non-US" modal from the "landing" page.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/64180728-f5140d80-ce6d-11e9-82d1-1dcf086a2262.gif)

**Comment by bakulf** [comment]
This dialog has been removed.

**Comment by SoftVision-LorandJanos** [comment]
As WebRTC blocking has been removed in v18, I'm marking this Wontfix issue.
