### ISSUE TITLE
FPN has encountered an unknown issue. Try turning it off, then on again. [v0.8]

### ISSUE THREAD

**Issue by pdehaan** [mozilla/secure-proxy#586]
Via [Slack](https://mozilla.slack.com/archives/CM2Q7BVHA/p1567523308052700),

**Jonathan Almeida Today at 8:08 AM**
"FPN has encountered an unknown issue. Try turning it off, then on again."

5 replies

**Jonathan Almeida  4 hours ago**
I tried turning it off and on again but it kept showing that error. I then realized it broke all the secure sites.
Firefox kept showing "Secure Connection Failed" (edited)

**Peter Saint-Andre  4 hours ago**
I had the same thing and needed to restart Nightly.

**Jonathan Almeida  3 hours ago**
Works! Although I'm not sure if that was helpful for anyone that wanted to debug the issue.

**Peter Saint-Andre  3 hours ago**
Yeah I know...

**Comment by bakulf** [comment]
Fixed
