### ISSUE TITLE
nip.io, a wildcard DNS service, doesn’t work for local development with FPN [v0.8]

### ISSUE THREAD

**Issue by pdehaan** [mozilla/secure-proxy#587]
Via [Slack](https://mozilla.slack.com/archives/CM2Q7BVHA/p1567529850054500),

**jwhitlock Today at 9:57 AM**
https://nip.io/, a wildcard DNS service, doesn’t work for local development with FPN

the way this service works is that you can encode the IP address in the domain name

for example http://127.0.0.1.nip.io:8081 is a webservice running on localhost at port 8081

with FPN enabled, I’m unable to make this connection. If I use a different browser or disable it, the connection to localhost works

we use this to avoid other development workarounds, like editing /etc/hosts, and we can create a self-signed certificate  if needed.

**Comment by bakulf** [comment]
We now support the proxy passthrough setting. Let's close this bug.
