### ISSUE TITLE
Is FPN really off? [v0.8]

### ISSUE THREAD

**Issue by pdehaan** [mozilla/secure-proxy#597]
Via [Slack](https://mozilla.slack.com/archives/CM2Q7BVHA/p1567617922065400),

**Michael Verdi 10:25 AM**
Is FPN really off?

<img width="1867" alt="Screen Shot 2019-09-04 at 12 23 05 PM" src="https://user-images.githubusercontent.com/557895/64285066-d7978000-cf0f-11e9-867c-c00698265d20.png">

**Comment by bakulf** [comment]
Fixed in the latest PRs
