### ISSUE TITLE
Interesting gmail (work gmail) error message this morning with FPN [v0.8]

### ISSUE THREAD

**Issue by pdehaan** [mozilla/secure-proxy#598]
Via [Slack](https://mozilla.slack.com/archives/CM2Q7BVHA/p1567609064064800),

**Liz Henry Today at 7:57 AM**
Interesting gmail (work gmail) error message this morning with FPN:

> **Corrupted Content Error**
> The site at https://mail.google.com/mail/u/0/#inbox has experienced a network protocol violation that cannot be repaired.
> The page you are trying to view cannot be shown because an error in the data transmission was detected.
>   Please contact the website owners to inform them of this problem.

**Comment by bakulf** [comment]
Fixed.
