### ISSUE TITLE
Cannot sign in/up on the “Firefox Private Network” extension on the latest Nightly build

### ISSUE THREAD

**Issue by SoftVision-SimonaRosu** [mozilla/secure-proxy#600]
[Affected versions]:
- Nightly 71.0a1 (Build ID: 20190904163258) (64-bit)

[Affected Platforms]:
- Mac 10.14
- Windows 10 x64
- Ubuntu 16.04 x64.

[Prerequisites]:
- Have the latest version of the “Firefox Private Network” add-on (v 0.9) installed.
- Have the browser location set to US.
- Have valid FxA credentials.
        
[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Click on the “Firefox Private Network” toolbar button.
3. Click on the “Sign in” button and log in with your credentials from prerequisites.
4. Observe the behavior.

[Expected result]:
- You are successfully signed in and the “Firefox Private Network” extension is on.

[Actual result]:
- You are not signed in.

[Regression Window]
-  The issue is not reproducible with older Nightly 70.0a1 (2019-09-04) builds. Considering this, using mozregression tool I have found the issue that broke this in the latest Nightly build. Here are the results:
 - Pushlog: https://tinyurl.com/y5dwuesb 
 - Last good revision: 0c0302b3db462a8a021ac059c192852b9be107cd
 - First bad revision: 71d1cf219835d41243530c6ba3ba730783f6ac25

From this pushlog it seems that bug 1405971 introduced this behavior.

[Notes]:
- Attached a screen recording with the issue.

![FPN_SignIn](https://user-images.githubusercontent.com/50919288/64342904-29b1d180-cff4-11e9-9bd0-04b43bb04337.gif)

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Private Network" add-on (v10 from 09/16/2019) installed, on the latest Firefox Nightly (71.0a1 Build ID - 20190916093313). Verified on Windows 10 x64, Mac 10.14.6 and Arch Linux 4.16.6 x64.
