### ISSUE TITLE
Waking  computer up from sleep with the proxy on and all page loads go to "Secure Connection Failed" page [v0.9]

### ISSUE THREAD

**Issue by pdehaan** [mozilla/secure-proxy#602]
Via [Slack](https://mozilla.slack.com/archives/CM2Q7BVHA/p1567690569093500),

**John Gruen 6:36 AM**
hey @bakulf woke my comp up from sleep with the proxy on and all page loads go to:

<img width="1159" alt="Screen Shot 2019-09-05 at 3 35 06 PM" src="https://user-images.githubusercontent.com/557895/64356912-84c5d300-cfb8-11e9-954a-6307475507f4.png">

disabling the proxy solved the issue, but it’s also booted my from being authenticated
and i cannot re-sign in
would it be useful to dump my extension logs somewhere?

**Andrea Marchesini 6:45 AM**
yes, enable the log and send them to me, please.
reloading the page produced the same results?

**John Gruen 6:46 AM**
yes

**Comment by bakulf** [comment]
This should be fixed in v11
