### ISSUE TITLE
The survey triggered after removing the extension doesn't contain any question

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/secure-proxy#605]
[Affected versions]:
- Firefox Release 69.0 
- Firefox Beta 70.0b3
- Firefox Nightly 71.0a1

[Affected Platforms]
- All Windows 
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the "Firefox Private Network" extension installed.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Navigate to "about:addons" page and select the "Extensions" section.
3. Remove the "Firefox Private Network" extension.
4. Observe the opened survey.

[Expected results]:
- A few questions are displayed on the first page of the survey.

[Actual results]:
- The "Thank you for taking this short survey. Your responses are important for making Firefox better" message is displayed in the survey even if there are no questions displayed.

[Notes]:
- After clicking the "Submit" button you are redirected to the survey is completed and the "Thank you for your response!" message is displayed even if there were no questions displayed on the previous page.
- Here is  a screen recording with the issue:
![no questions in survey](https://user-images.githubusercontent.com/19226534/64423812-0d736a80-d0b0-11e9-8177-dd0365d68961.gif)

**Comment by bakulf** [comment]
@johngruen is this resolved? Can we close this bug?

**Comment by madalincm** [comment]
Issue no longer reproducing. Marking as verified fixed
