### ISSUE TITLE
Unable to use Google Hangouts until uninstalling add-on [v0.9]

### ISSUE THREAD

**Issue by pdehaan** [mozilla/secure-proxy#612]
Via [Slack](https://mozilla.slack.com/archives/CM2Q7BVHA/p1568139793137100),

**bballo 11:23 AM**
Tried v0.9 of the addon today. Worked fine until I had to use Google Hangouts video chat. I got a dialog warning me that it may not work unless I disable it in that tab. I did so, but Hangouts continued to not work until I disabled Private Network for all tabs.

**Comment by theres-waldo** [comment]
Note, I didn't have to uninstall the addon to get Hangouts to work, I just had to disable it for all tabs (rather than just the Hangouts tab).

**Comment by bakulf** [comment]
This should be fixed in the latest versions.
