### ISSUE TITLE
Integrate /welcome into the add-on

### ISSUE THREAD

**Issue by betsymi** [mozilla/secure-proxy#617]
Integrate this page into the extension, with the following changes:

Opt out link should no longer go to SUMO, but expand below the content. [Here is the UX for how this should look](https://designakt.github.io/SecureProxyBeta-PrivacyNotice/Firefox%20Private%20Network.html#instruction).

**How to opt out of sending technical data**

  1. Click the menu button {menu} and choose Preferences in Mac or Options in PC
  2. Select Privacy & Security on the left
  3. Scroll down to Firefox Data Collection and Use
  4. Uncheck Allow Firefox to send technical and interaction data to Mozilla

There are also a couple of string changes:

| Correct String       | Incorrect String           | Location  |
| ------------- |-------------| -----|
| It does this by encrypting the web addresses you visit. | It does this by encrypting the web addresses you visit and the data you send to most websites. | 1st paragraph |
| You may opt out of sharing this data with us at any time. | You may opt out of sharing this data with us at anytime. | 2nd paragraph |

**Comment by pdehaan** [comment]
@betsymi How urgent are the string changes? Should we do them on the private-network site and try and get them in a deploy early next week? /cc @lesleyjanenorton
