### ISSUE TITLE
Firefox Private Network breaks apple verification / 2fa [v0.9]

### ISSUE THREAD

**Issue by pdehaan** [mozilla/secure-proxy#624]
Via [Slack](https://mozilla.slack.com/archives/CM2Q7BVHA/p1568345313199500),

**Sarah Bird 8:28 PM**
BUG REPORT: Firefox Private Network breaks apple verification / 2fa. (FF69)

Steps to reproduce:
1. go to beta.music.apple.com
2. click sign-in, pop-up window appears
3. enter apple id and password
expected: with ff private network off:
4. verification pop up appears on phone, click allow
5. pop up on phone changes to a 2fa 6 digit code to enter
6. login panel in browser updates to input 6 digit code
7. enter 6 digit code, and get logged in
actual: with ff private network on:
4. verification pop up appears on phone, click allow
5. pop up on phone changes to a 2fa 6 digit code to enter
6. login panel does not update, login cannot proceed

**Comment by bakulf** [comment]
This should be fixed in v17.
