### ISSUE TITLE
Had to switch it on after "an unknown error occurred"; enabling it gave me little feedback and it stayed off [v0.9]

### ISSUE THREAD

**Issue by pdehaan** [mozilla/secure-proxy#626]
Via [Slack](https://mozilla.slack.com/archives/CM2Q7BVHA/p1568315452187000),

**Harald Kirschner 12:10 PM**
Had to switch it on after "an unknown error occurred"; enabling it gave me little feedback and it stayed off

<img width="330" alt="image (10)" src="https://user-images.githubusercontent.com/557895/64879464-def31380-d60a-11e9-90e7-4b5515fabe07.png">

Later changed to login-needed state; but only after closing and opening the panel again

**Comment by bakulf** [comment]
Fixed in b17.
