### ISSUE TITLE
Firefox fails to check for all extensions updates with FPN enabled after reconnecting to router

### ISSUE THREAD

**Issue by Fanolian** [mozilla/secure-proxy#627]
Disclaimer: I do not live in US but I tried with a US IP address with VPN and the issue persists.

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0
Build ID: 20190913092859
FPN 0.9

### Steps to reproduce
0. Install FPN in a new profile. Log in with a Firefox Account. Enable FPN.
1. Go to *about:addons* > *Extensions*
2a. (Optional) Click the gear on the right, uncheck `Update Add-ons Automatically`.
2b. (Optional) Install an old version of any extension, like [Facebook Container 2.0.1](https://addons.mozilla.org/firefox/addon/facebook-container/versions/).
3. Click the gear. Click `Check for Updates`. It should work for now.
4. Disconnect from and reconnect to router in Windows. (I use WiFi)
5. `Check for Updates` again.

### Actual results
Firefox fails to check for updates and immediately displays `No updates found`. It is easy to verify if step 2 is included.
2 log messages appear in *Browser Console* when I click `Check for Updates`:
```
1568391183583	addons.update-checker	WARN	HTTP Request failed for an unknown reason
1568391183586	addons.productaddons	WARN	Failed downloading XML, status: 0, reason: error
```
If I turn off FPN and check for extension updates, Nightly can find the updates and no log messages are generated in *Browser Console*. The issue is fixed temporary only when I restart the browser.

**Comment by bakulf** [comment]
Dup of #621
