### ISSUE TITLE
Firefox Private Network Connection encountered an unknown problem

### ISSUE THREAD

**Issue by uBlock-user** [mozilla/secure-proxy#632]
Starts with Connecting to secure server... and gets stuck at "Firefox Private Network Connection encountered an unknown problem", whats wrong and why is it not working ?

**Comment by bakulf** [comment]
Does it happen always or just with particular internet connections? For instance where a captive portal is needed?

**Comment by uBlock-user** [comment]
> Does it happen always 

Yes always. I'm on Firefox 71 if that helps.

**Comment by bakulf** [comment]
Can I ask you to check if in the browser console there is anything suspicious? Can you send me the logs from there? Thanks!

**Comment by uBlock-user** [comment]
My connection also stops working after it fails to connect.

Nothing in browser console, so I went to about:debugging and Inspected the extension console itself which spewed this --

![image](https://user-images.githubusercontent.com/21290713/64958821-8d1de800-d8ad-11e9-9ebc-77de4f894236.png)

**Comment by uBlock-user** [comment]
I must add I have DoH enabled on Firefox with TRR mode set to 2 and server set to `cloudflare-dns.com`
