### ISSUE TITLE
Issue with the login page for USPS.com [v0.9]

### ISSUE THREAD

**Issue by pdehaan** [mozilla/secure-proxy#633]
Via [Slack](https://mozilla.slack.com/archives/CM2Q7BVHA/p1568478033005800?thread_ts=1568222032.153100&cid=CM2Q7BVHA),

**Keith Willowhawk 9:20 AM**
Issue with the login page for USPS.com (US postal service) with FPN on, page won’t render.  FPN off it renders.  Console and Network logs attached.

[usps.com_fpn.zip](https://github.com/mozilla/secure-proxy/files/3614899/usps.com_fpn.zip)

**Comment by bakulf** [comment]
@mayhemer can you take a look at the network log?

**Comment by mayhemer** [comment]
I can see one GET request to `https://reg.usps.com/portal/login?` with numerous arguments and with numerous cookies.  We create a new proxied, double encrypted connection, as expected.  `reg.usps.com` talks h2.  There is a reply to the HTTP request from the http server, and it is `405 Method Not Allowed` with `content-length: 0`.  Hence the blank page.  Why the server replies this way is not clear.  Could be something with too many requests from a single IP (the Cloudflare proxy node for the region) or something with geolocation.  Note that `reg.usps.com` is provided by akamai (at least in Czech Republic).

This is not a connectivity problem on our side.

**Comment by bakulf** [comment]
This bug should be fixed in v17.

**Comment by bakulf** [comment]
This bug should be fixed in v17.
