### ISSUE TITLE
The "Firefox Private Network" doorhanger is not opened if the toolbar button is clicked while the notification is still displayed

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/secure-proxy#642]
**[Affected versions]:**
- Firefox Release 69.0 and above

**[Affected Platforms]:**
- All Windows
- All Linux
- All Mac

**[Prerequisites]:**
- Have a new Firefox profile with the latest version (v10) of the "Firefox Private Network" add-on installed.
- You are logged in to the "Firefox Private Network".
	
**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://www.messenger.com/".
2. Click the "Turn Off in This Tab" button from the "WebRTC" modal and open a new tab.
3. Go back to the previous tab an click the "Firefox Private Network" toolbar button while the notification is still displayed.
4. Observe the behavior.

**[Expected result]:**
- The "Firefox Private Network" doorhanger is opened.

**[Actual result]:**
- The notification is dismissed but the "Firefox Private Network" doorhanger is not opened.

**[Notes]:**
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/65053754-25cb6b00-d975-11e9-9fb6-12726f9a7df3.gif)

**Comment by bakulf** [comment]
WebRTC blocking has been removed in v18. This bug is now invalid.

**Comment by SoftVision-LorandJanos** [comment]
Based on the comment above, I'm marking this QA Wontfix issue.
