### ISSUE TITLE
"Performing a TLS handshake to github.com"

### ISSUE THREAD

**Issue by davismtl** [mozilla/secure-proxy#644]
Over the last week or so, I intermittently can’t load Github pages. After many attempts, it might eventually work but I essentially see this and Github just doesn't load. (5 mins of refreshing might eventually work)

![image](https://user-images.githubusercontent.com/19537086/65196941-12340900-da36-11e9-90a6-e79b4c17cdb8.png)

I've identified through some friendly help on[ this thread ](https://mozilla.slack.com/archives/C4D3JFF26/p1568849349067000) that FPN seems to be the culprit. If I turn off FPN when Github won't load, it starts to work again.

When I experience the problem, other sites still seem to work. I'm not sure what's happening with Github's certificate specifically.

I'm running v0.9. I'm in Canada so I'm not sure if that is the latest version.

**Comment by mayhemer** [comment]
Thanks for reporting this.  If you still can reproduce this, can you please [provide logs](https://developer.mozilla.org/en-US/docs/Mozilla/Debugging/HTTP_logging)?

**Comment by bakulf** [comment]
Close this issue for inactivity.
