### ISSUE TITLE
Define the beta time slots for the footer

### ISSUE THREAD

**Issue by bakulf** [mozilla/secure-proxy#649]
The flow shows: "Beta ends next week". But what about if beta ends this week? or the next next week?
@betsymi can you help me here? Thanks!

**Comment by betsymi** [comment]
I think it is best to avoid using specific dates or time periods in the extension panel. We can communicate those on the website once we know them for certain. My recommendation is to use the following string here:

Beta is ending soon. [Learn more](url)

**Comment by bakulf** [comment]
> Beta is ending soon. [Learn more](url)

Great! We need to decide when this message should be shown. 1 week before?
