### ISSUE TITLE
SSO login failure (intermittent)

### ISSUE THREAD

**Issue by agashlin** [mozilla/secure-proxy#659]
My mozilla.com SSO LDAP login, with a second factor hardware token, was repeatedly failing after I entered the code from the token. It kept saying "Your session has expired, please try again (Dismiss)" (or something similar), both when trying to log in to mana.mozilla.org and sso.mozilla.com. When I turned off FPN (v11) it worked immediately.

I haven't been able to reproduce this yet, I tried again with the same profile and on a fresh one, so it may have been a coincidence. Maybe I ended up at a working auth endpoint when I accessed it directly.

**Comment by pdehaan** [comment]
(Via [Slack](https://mozilla.slack.com/archives/CM2Q7BVHA/p1569442603058700))

**Comment by bakulf** [comment]
Fixed
