### ISSUE TITLE
FPN prevents Firefox update check

### ISSUE THREAD

**Issue by agashlin** [mozilla/secure-proxy#663]
STR:

1. With a fresh install of Nightly (on 64-bit Windows 10), install FPN v11, log in
2. Enable update logging by setting `app.update.log`
3. Restart Nightly
4. Open the About Nightly dialog to check for updates. It will say "Nightly is up to date"
5. Check the browser console, there will be an error like:

```
AUS:SVC Checker:onError - request.status: 2153394078
AUS:SVC Checker:onError - Getting secInfo failed.
AUS:SVC getStatusTextFromCode - transfer error: Update XML file malformed (200), default code: 200
```

Turning off FPN seems to fix it.

This seems to be the relevant part of the network log:
```
E/nsSocketTransport nsSocketTransport::OnSocketReady [this=000002A3D7134000 outFlags=3]
D/nsSocketTransport nsSocketOutputStream::OnSocketReady [this=000002A3D71342B0 cond=0]
V/nsHttp nsHttpConnection::OnSocketWritable [this=000002A3D7135800] host=aus5.mozilla.org
V/nsHttp nsHttpConnection::GetSecurityInfo trans=000002A3CFB62C00 tlsfilter=0000000000000000 socket=000002A3D7134018
E/nsHttp nsHttpTransaction::OnSocketStatus [this=000002A3CFB62C00 status=804b000c progress=0]
V/nsHttp nsHttpConnection::EnsureNPNComplete [this=000002A3D7135800] setting complete to true
E/nsHttp nsHttpTransaction::OnSocketStatus [this=000002A3CFB62C00 status=804b000d progress=0]
V/nsHttp   writing CONNECT request stream
D/nsSocketTransport nsSocketOutputStream::Write [this=000002A3D71342B0 count=1138]
D/nsSocketTransport   calling PR_Write [count=1138]
D/nsSocketTransport   PR_Write returned [n=-1]
D/nsSocketTransport ErrorAccordingToNSPR [in=-12190 out=805a2f9e]
D/nsSocketTransport nsSocketTransport::OnMsgOutputClosed [this=000002A3D7134000 reason=805a2f9e]
V/nsHttp nsHttpConnection::OnSocketWritable 000002A3D7135800 ReadSegments returned [rv=0 read=0 sock-cond=805a2f9e again=1]
V/nsHttp nsHttpConnection::CloseTransaction[this=000002A3D7135800 trans=000002A3CFB62C00 reason=805a2f9e]
V/nsHttp   closing associated mTransaction
V/nsHttp nsHttpTransaction::Close [this=000002A3CFB62C00 reason=805a2f9e]
V/nsHttp nsHttpConnectionMgr::RemoveActiveTransaction t=000002A3CFB62C00 tabid=0(0) thr=0
V/nsHttp Active transactions -[0,0,0,0]
```

I think -12190 is -0x3000 + 98, [SSL_ERROR_PROTOCOL_VERSION_ALERT](https://searchfox.org/mozilla-central/rev/23f836a71cfe961373c8bd0d0219ec60a64b3c8f/security/nss/lib/ssl/sslerr.h#162).

Earlier in the log I noticed this `BE_CONSERVATIVE` flag being set:

```
V/nsHttp Creating nsHalfOpenSocket [this=000002A3D96DA2F0 trans=000002A3D8EC88D0 ent=aus5.mozilla.org key=TS....C.[tlsflags0x00000000]aus5.mozilla.org:443 (https:firefox.factor11.cloudflareclient.com:2486)[:]{CIK 47fdb3325f77ddb70}]
V/nsHttp nsHalfOpenSocket::SetupStreams [this=000002A3D96DA2F0 ent=TS....C.[tlsflags0x00000000]aus5.mozilla.org:443 (https:firefox.factor11.cloudflareclient.com:2486)[:]{CIK 47fdb3325f77ddb70}] setup routed transport to origin aus5.mozilla.org:443 via :443
D/nsSocketTransport creating nsSocketTransport @000002A3D7134000
E/nsSocketTransport nsSocketTransport::Init [this=000002A3D7134000 host=aus5.mozilla.org:443 origin=aus5.mozilla.org:443 proxy=firefox.factor11.cloudflareclient.com:2486]
V/nsHttp Setting Socket to BE_CONSERVATIVE
D/nsSocketTransport nsSocketTransport::SetConnectionFlags 000002A3D7134000 flags=612
```

When I remove that [in the update service](https://searchfox.org/mozilla-central/rev/23f836a71cfe961373c8bd0d0219ec60a64b3c8f/toolkit/mozapps/update/UpdateService.jsm#3952-3955), it seems to work. The purpose is to not use TLS 1.3 (and maybe other "newer protocol features"?).

I don't know much about how TLS connections get set up, but my guess is that setting this causes a connection to the proxy to fail as it doesn't support TLS 1.3 for talking to the proxy. This seems supported by what I see in Wireshark: the browser doesn't send `supported_versions`. When I disable setting `beConservative`, it sends `supported_versions` with 1.2 and 1.3.

It seems like this shouldn't affect the connection with the proxy itself, though; I'd have thought that would only affect the inner TLS connection to aus5.mozilla.org. As such this *might* be a Firefox bug rather than something FPN needs to fix. `beConservative` is used in a few other places as well, such as blocklist and addon checking, and maybe telemetry? It also seems odd that this isn't causing more trouble in those cases; maybe it's sometimes able to use an existing connection to the proxy?

**Comment by agashlin** [comment]
I filed [bug 1585236](https://bugzilla.mozilla.org/show_bug.cgi?id=1585236) in case this needs to be handled in the browser.

I notice that if I first go into about:addons and check for updates there, subsequent browser update checks via the About dialog will work. So it isn't failing all the time (which makes sense, a few other people I asked to look before I had a proper STR didn't notice the errors). Maybe it's the combination of `beConservative` with some other flags that's breaking the connection made by the update service, but it can reuse the connection made by the addon update check?

**Comment by mayhemer** [comment]
In [bug 1585236](https://bugzilla.mozilla.org/show_bug.cgi?id=1585236) I proposed a patch that introduces a preference to connect the proxy w/o non-conservatively regardless of what has been set on the channel.

The addon will have to flip (and revert on uninstall/disable) the pref.

The pref name is `network.http.proxy.respect-be-conservative`, default at `true`.  The addon has to flip it to `false`.
