### ISSUE TITLE
When a time-limited session ends, pause browser connections to warn user

### ISSUE THREAD

**Issue by arthur-mozilla** [mozilla/secure-proxy#672]
After Skyline: we should consider how to prevent leaks when a time-limited session ends. Ideally, we should tell users and prevent any unproxied connections until the user confirms they want to proceed.

**Comment by bakulf** [comment]
In v16, we notify the user 5 minutes before the token expiration.

**Comment by arthuredelstein** [comment]
Thanks @bakulf. If the user ignores the warning 5 min in advance, are browser connections paused, or do they just go unproxied?
