### ISSUE TITLE
Secure Proxy passes do not update properly for the same user

### ISSUE THREAD

**Issue by bsurd** [mozilla/secure-proxy#683]
#### Affected Platforms:
- Linux Ubuntu 19.04 (64-bit)
- Windows 10 (64-bit)
- MacOS 10.14

#### Precondition
- Have SP installed in 2 FF windows or on two different machines.

#### Steps to reproduce
1. Log in on machine one or the first instance of FF and use up 3 of your passes until you have only one pass remaining.
2. Log in with the same account on machine two or the second instance of FF and use up the last pass.
3. Go to the first window/machine and try to enable SP.

#### Expected result:
- The interface updates and the user can see that he has no more passes.

#### Actual result:
- The interface remains the same and the user still sees that he has one pass. This could be confusing for users who have multiple devices.

![21](https://user-images.githubusercontent.com/17178945/66493032-0c25cb00-eabe-11e9-883a-fa3062de1ec6.png)
![incorectNumberOfPassesDisplayed](https://user-images.githubusercontent.com/17178945/66493060-121bac00-eabe-11e9-9cec-cd3b1d20c470.gif)

**Comment by bakulf** [comment]
This is correct. But as soon as the user tries to use the token, the extensions will be in sync again.
I don't think we can do better than this for the 22nd...

**Comment by bakulf** [comment]
This should be fixed in v16. @bsurd can you test it again?

**Comment by bsurd** [comment]
Verified in v17, this issue is no longer reproducible. The interface is properly updated avoiding any sort of confusion.
