### ISSUE TITLE
Improve login window trigger responsiveness 

### ISSUE THREAD

**Issue by bsurd** [mozilla/secure-proxy#699]
#### Affected Platforms:
- Linux Ubuntu 19.04 (64-bit)
- Windows 10 (64-bit)
- MacOS 10.14

#### Precondition
- Have SP installed.

#### Steps to reproduce
1. Open the SP doorhanger.
2. Click on the "Continue" button.

#### Expected result:
- The login window is displayed almost instantly. 

#### Actual result:
- The login window takes ~1 second at times before it's displayed.

![1](https://user-images.githubusercontent.com/17178945/66644179-f7197b00-ec28-11e9-916f-8488c580c512.gif)

**Comment by bakulf** [comment]
I suggest to do 2 things:

1. avoid multiple clicks
2. show a loading icon.

**Comment by bakulf** [comment]
This is part of v16.

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible on the latest Secure Proxy add-on (v17), using the latest Firefox  Nightly (72.0a1). Verified on Windows 10 x64.
