### ISSUE TITLE
The learn more link should not be displayed in the login screen

### ISSUE THREAD

**Issue by bsurd** [mozilla/secure-proxy#701]
#### Affected Platforms:
- Linux Ubuntu 19.04 (64-bit)
- Windows 10 (64-bit)
- MacOS 10.14

#### Precondition
- Have SP installed.

#### Steps to reproduce
1. Open the SP doorhanger.
2. Observe the UI.

#### Expected result:
- The "Changes are coming to beta. Learn more" is not displayed.

#### Actual result:
- The "Changes are coming to beta. Learn more" is displayed.

#### Notes:
- The "Changes are coming to beta. Learn more" should only be displayed after a user has logged in according to the [mocks](https://mozilla.invisionapp.com/share/P5RW39B4YB8#/screens).

![1](https://user-images.githubusercontent.com/17178945/66644879-b7ec2980-ec2a-11e9-8b42-1813a499bd6f.jpg)

**Comment by bakulf** [comment]
I actually decided to show the footer only after the authentication because otherwise, the extension will not be able to hide it after the 22nd. I discussed this with @brassy- . Do you think it's acceptable to remove the footer from the authentication page?

**Comment by bakulf** [comment]
Currently, the footer has been removed. This issue is not valid anymore.

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible using the latest Secure Proxy version (v0.13), with the latest Firefox Release (70.0), Beta (71.0b3) and Nightly (72.0a1). Verified on Windows 10 x64, Mac 10.14.2 and Linux Ubuntu 16.04 x64.
