### ISSUE TITLE
FxAUtils.obtainFxaCode() races with wellKnownData fetch

### ISSUE THREAD

**Issue by mayhemer** [mozilla/secure-proxy#703]
FxAUtils.obtainFxaCode should wait for the fetch initiated in wellKnownData.fetch() started (and not being wait for) from main.init() > FxAUtils.init() > wellKnownData.init().  Otherwise, various FXA_ENDPOINT_* entries may not be available when queried from FxAUtils.obtainFxaCode via wellKnownData.getIssuerEndpoint() during authentication started as a reaction to `View.sendMessage("authenticate")`.

**Comment by bakulf** [comment]
Any wellknowndata.get*Endpoint() function is async and it does the fetch() if needed.
See: https://github.com/mozilla/secure-proxy/blob/9ed075a9d00a467287773d86e6b784dfca2143ef/src/background/wellKnownData.js#L140 
That wellKnownData.init() is mainly to obtain the FxA openID URL.

**Comment by mayhemer** [comment]
Missed that bit!  Excellent.
