### ISSUE TITLE
User is not able to log off and relog with a different account

### ISSUE THREAD

**Issue by madalincm** [mozilla/secure-proxy#707]
#### Affected Platforms:
- Linux Ubuntu 19.04 (64-bit)
- Windows 10 (64-bit)
- MacOS 10.14

#### Precondition
- Secure proxy is installed, user is logged in with fxa

#### Steps to reproduce
1. Open the SP doorhanger and click on the gear icon
2. Click on the manage account link
3. Log out from firefox accounts
4. Open again the SP doorhanger

#### Expected result:
- The user is logged off from the Secure Proxy. If he wants he is able to log it with another account

#### Actual result:
- He is still logged in with the initial account, there is not option to log in with a different account
![imposibleToChangeAccounts](https://user-images.githubusercontent.com/15685441/66749316-3696d000-ee92-11e9-97e0-19536fb739fe.gif)

**Comment by bakulf** [comment]
The logout is not implemented and we are not planning to do it.
@arthur-mozilla am I right?

**Comment by arthuredelstein** [comment]
Not planning to do it now. Possibly later.

@madalincm, thanks for reporting this. Could you describe why you would like this feature? Thank you in advance.

**Comment by madalincm** [comment]
@arthuredelstein  The use cases that I had in mind when logging this issues are related to the fact that the user might want to use a different fxa account. There are different reasons why that might happen:
- the user decides to use a different fxa account because he lost his access to the email account
- that email account is compromised 
- he is changing his email provider

**Comment by bakulf** [comment]
See #391

**Comment by madalincm** [comment]
> See #391

Marking as duplicate per above comment.
