### ISSUE TITLE
Secure proxy allowed to run in private mode without user giving permission 

### ISSUE THREAD

**Issue by madalincm** [mozilla/secure-proxy#708]
#### Affected Platforms:
- Linux Ubuntu 19.04 (64-bit)
- Windows 10 (64-bit)
- MacOS 10.14

#### Precondition
- none

#### Steps to reproduce
1. Drag and drop the SP signed xpi to install it
2. Observe the door hangers that are displayed
3. Open the addons manager and observe the secure proxy add-on

#### Expected result:
- At install time a door hanger is displayed asking for permission for SP to run in private mode. If the user does not opt in when opening addons manager the SP add-on does not have the allow in private mode icon 

#### Actual result:
- No door hanger to give private mode permission is displayed. After install in addons manager SP has the allow in private mode icon

![allowedInPrivateModeByDefault](https://user-images.githubusercontent.com/15685441/66750557-714e3780-ee95-11e9-9990-df36fe50ee5c.gif)

**Comment by bakulf** [comment]
@mixedpuppy is this a real bug?

**Comment by mixedpuppy** [comment]
> @mixedpuppy is this a real bug?

No.  Privileged extensions get private browsing automatically, IIRC you cannot remove that permission either.

**Comment by bakulf** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1588536

**Comment by bakulf** [comment]
Ok. let's close this bug.

**Comment by SoftVision-LorandJanos** [comment]
I will mark this as Wontfix.
