### ISSUE TITLE
Secure Proxy icon does not update properly if a user is not logged in

### ISSUE THREAD

**Issue by bsurd** [mozilla/secure-proxy#709]
#### Affected Platforms:
- Linux Ubuntu 19.04 (64-bit)
- Windows 10 (64-bit)
- MacOS 10.14

#### Precondition
- Have an older version of SP installed and don't log in with any user.

#### Steps to reproduce
1. Update SP to the latest version.

#### Expected result:
- The icon is updated to the v12 version.

#### Actual result:
- There is a noticeable flicker where the icon switches to the new version but then reverts back to the old one.

#### Notes:
- This issue is reproducible intermittently.
- The icon switches to the correct version of SP after FF is restarted.

![1](https://user-images.githubusercontent.com/17178945/66750989-97c0a280-ee96-11e9-8524-fa885daca050.gif)

**Comment by bakulf** [comment]
This seems a platform bug. @mixedpuppy, do you know if there is anything to do here?

**Comment by mixedpuppy** [comment]
Or maybe the icon is cached somewhere.  In any case, move this bug over to bugzilla.

**Comment by bakulf** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1588536
