### ISSUE TITLE
Secure Proxy can be used in any country if the user logs in using credentials used at least once in the US

### ISSUE THREAD

**Issue by heres-maria** [mozilla/secure-proxy#711]
#### Affected Platforms:
- Windows 10 (x64)

#### Precondition
- Secure Proxy is installed and you are logged in. Your geolocation is set to be inside the US.
	
#### Steps to reproduce
1. Close Firefox.
2. Change your geolocation to appear anywhere other than the US.
3. Reopen Firefox.

#### Expected result:
- The FPN doorhanger displays the message "At this time, Firefox Private Network is not available in your region. You must be in the United States to complete the setup process." and the add-on can not be used.

#### Actual result:
- The doorhanger displays FPN as being "ON" and the message "Your connection is secure, and your location is hidden from websites and trackers, making it tougher for those annoying targeted ads to follow you around online." is displayed.

#### Notes:
- This is reproducible for any account that has been used at least once to log into FPN inside the US, regardless of the geolocation at the moment of its creation.
- The issue is also reproducible if the user logs into FPN from another device outside the US using the account once used in the US.
- The issue also seems to be reproducible if the user changes the geolocation while using the add-on.

**Comment by bakulf** [comment]
This bug is invalid. Secure-proxy can be used outside the US if the _first_ authentication was done with an IP address from the US. @stpeter can you confirm this?

**Comment by stpeter** [comment]
I confirm the comment from @bakulf - it is a core use case that a person can travel to another location and continue to use FPN, as long as the initial authentication happened within an approved location (currently the U.S. only).
