### ISSUE TITLE
Doorhanger links to new URL

### ISSUE THREAD

**Issue by rbillings** [mozilla/secure-proxy#714]
The end-of-beta release includes a doorhanger option for "How passes work" that directs users to the new URL.

Discussion in Slack whether it should redirect.

**Comment by rbillings** [comment]
Redirect URL: https://private-network.firefox.com/beta-announcement

**Comment by madalincm** [comment]
Please note that in about:addons in the installed add-on detail page at the Homepage section the new page is displayed:
![homepageLink](https://user-images.githubusercontent.com/15685441/66811469-d0fe1e80-ef39-11e9-9b94-8bf67cc4f813.png)

**Comment by bakulf** [comment]
We still need the redirect of https://fpn.firefox.com/browser to https://private-network.firefox.com
