### ISSUE TITLE
The notification displayed when returning to a WebRTC site where FPN was turned off from the modal changes color right before closing

### ISSUE THREAD

**Issue by heres-maria** [mozilla/secure-proxy#719]
#### Affected Platforms:

-  Windows 10 (64-bit)
-  Mac 10.15
#### Precondition

- Secure proxy is installed and the user is logged in.

#### Steps to reproduce
1. Go to Messenger.
2. Select the "Turn off for This Site" option in the modal.
3. Open a new tab and after go back to the previous one.
4. Wait for the notification to disappear.

#### Expected result

- The toast notification remains yellow the entire time it is visible on the screen.

#### Actual result:

- The notification turns blue and the warning sign triangle inside it disappears right before it closes.

#### Notes

- This issue wasn't reproducible on Linux Ubuntu 16.04.
- I have attached a screen recording of the issue:

![color change](https://user-images.githubusercontent.com/53752296/66828752-82ad4780-ef5a-11e9-828a-28e352cbe9ab.gif)

**Comment by bakulf** [comment]
Acutally this is a bug in the extension

**Comment by bakulf** [comment]
WebRTC blocking has been removed in v18. This bug is now invalid.

**Comment by SoftVision-LorandJanos** [comment]
Based on the comment above, I'm marking this bug QA Wontfix issue.
