### ISSUE TITLE
Clicking the arrow from the country field does not open the drop down menu

### ISSUE THREAD

**Issue by madalincm** [mozilla/secure-proxy#720]
#### Affected versions:
- Firefox Release 69.0.1
- Firefox Beta 70.0b9
- Firefox Nightly 71.0a1

#### Affected Platforms:
- Windows 7 (64-bit)

#### Precondition
- none

#### Steps to reproduce
1. Open Join the VPN Waitlist page: https://stage.guardian.nonprod.cloudops.mozgcp.net/vpn/invite
2. Click on the black arrow from the country field 

#### Expected result:
- Clicking the arrow opens the country selector

#### Actual result:
- Clicking the arrow does not open the menu. Clicking anywhere else in the field does open the menu.
![countrySelector](https://user-images.githubusercontent.com/15685441/66830010-36afd200-ef5d-11e9-9040-fc1a810d2957.gif)

**Comment by madalincm** [comment]
Wrong repo. Logged the issue here: https://github.com/mozilla-services/guardian-website/issues/357

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible on [Join the VPN Waitlist](https://stage.guardian.nonprod.cloudops.mozgcp.net/vpn/invite) section of the FPN site, using the latest Firefox Release (70.0), Beta (71.0b3) and Nightly (72.0a1). Verified on Windows 10 x64, Mac 10.14.2 and Linux Ubuntu 16.04 x64.
