### ISSUE TITLE
Typos in the /browser page

### ISSUE THREAD

**Issue by madalincm** [mozilla/secure-proxy#722]
#### Affected versions:
- Firefox Release 69.0.1
- Firefox Beta 70.0b9
- Firefox Nightly 71.0a1

#### Affected Platforms:
- Windows 7 (64-bit)

#### Precondition
- none

#### Steps to reproduce
1. Open https://stage.guardian.nonprod.cloudops.mozgcp.net/browser and scroll to the Frequently asked questions section. 
2. Observe the text displayed at the Does Private Network log my browsing history? question

#### Expected result:
- No typos

#### Actual result:
- Firefox is committed to your protecting your privacy. (there is an extra your):
![image](https://user-images.githubusercontent.com/15685441/66831554-99ef3380-ef60-11e9-82cd-5d395aec3627.png)
- The full-device protection, provided in partnership with Mullvad, does not log nor monitor your or browsing or network history. (there is an extra or)
![image](https://user-images.githubusercontent.com/15685441/66831613-c3a85a80-ef60-11e9-8388-112eff18bf6a.png)

**Comment by bakulf** [comment]
We should move this issue to the correct repo.

**Comment by madalincm** [comment]
moved to guardian website repo. Closing this issue
