### ISSUE TITLE
Copy Updates for /welcome

### ISSUE THREAD

**Issue by betsymi** [mozilla/secure-proxy#727]
Per the updated time limit on the passes, these changes need to be made to the welcome page. We will also need new screenshots of the extension to add. 

| **❌ Incorrect Old String**        | **✅ Correct New String**           |
| ------------- |-------------|
| Once you’re signed in, you'll receive four passes a month of Private Network, each valid for three hours. | Once you’re signed in, you'll receive four passes a month of Private Network, each valid for eight hours.|
| Once you claim a pass, it runs for three hours, even if you turn Private Network off. | Once you claim a pass, it runs for eight hours, even if you turn Private Network off. |

**Comment by chrismore** [comment]
https://private-network.firefox.com/beta-announcement needs updated too

**Comment by bakulf** [comment]
This task has been completed in the extension. Beta-announcement page has been removed.
