### ISSUE TITLE
Turning private proxy on and off using a private window and a normal window alternatively sometimes leads to the doorhanger not showing the right state

### ISSUE THREAD

**Issue by heres-maria** [mozilla/secure-proxy#729]
#### Affected Platforms:

- Windows 10 (x64)

#### Precondition

- Secure Proxy is installed and you are logged in. 

#### Steps to reproduce

1. Open a private window alongside the normal one.
2. Click the "OFF" button in the private window.
3. Click the "ON" button in the normal window.

#### Expected result:

- In the last step, the doorhanger displays the "ON" state, with a blue background and the button set on "ON". 

#### Actual result:

- The doorhanger sometimes displays the "OFF" state, despite it being on. 

#### Notes:

- The issue seems to be intermittent. I have not been able to observe a definite pattern to this.
- This is also reproducible when the initial state is off, with the user turning it on in private browsing and turning it back off in the initial window.
- The blue message reading "Firefox Private Network is turned off/on" appears inconsistently, sometimes being displayed in the same window the doorhanger is open in, other times being displayed in the other window.
- Private Proxy does turn on, it just displays the wrong state immediately after clicking on the button. Closing and reopening the doorhanger leads to the right state being displayed.

![private + normal 1](https://user-images.githubusercontent.com/53752296/66897669-21d84a80-f000-11e9-8ce5-d141bf826149.gif)

**Comment by bakulf** [comment]
@jonathanKingston anything we can do here?

**Comment by heres-maria** [comment]
Considering this issue is still reproducible, should it be marked as "wontfix", or will something be done about it at a later time?

**Comment by madalincm** [comment]
@bakulf Should we add the wontifx flag here?
