### ISSUE TITLE
I can download and run the proxy from Canada

### ISSUE THREAD

**Issue by ehsan** [mozilla/secure-proxy#732]
In latest Firefox Nightly, I went to https://private-network.firefox.com/ and downloaded the latest extension and installed it from Canada and managed to activate the proxy successfully.  I believe this beta should be restricted to the US.

**Comment by pdehaan** [comment]
@ehsan Interesting! I'm also in Canada and I get the "This extension is currently available to US desktop users only." modal.

What location does it tell you when you go to https://whatismyipaddress.com/ or https://www.whatismyip.com/?

**Comment by stpeter** [comment]
Also note that (AFAIK) the version with geo-restrictions on signing in has been pulled back pending further guidance from leadership, so the fact that you're able to log in isn't necessarily a concern. The download is another story (did you have it installed before?).

**Comment by bakulf** [comment]
This seems like a bug in the geo-restriction code. Let's close this issue and let's continue the debugging in the guardian repo.

**Comment by ehsan** [comment]
> What location does it tell you when you go to https://whatismyipaddress.com/ or https://www.whatismyip.com/?

Interestingly it shows that I'm somewhere in the middle of the US (and I'm not!).  This is from the Mozilla Toronto office, FWIW.

Going to the website again now I get the "This extension is currently available to US desktop users only." modal...

**Comment by bsurd** [comment]
The issue does not seem to be reproducible anymore, checked with a VPN using different regions, including Canada and the modal was displayed every time. With v15 installed, can confirm that if a user outside of US somehow manages to get his hands on SP it will inform him that the extension is not available in his region. Marking this as verified.
