### ISSUE TITLE
FPN prevents treeherder logs from loading

### ISSUE THREAD

**Issue by dholbert** [mozilla/secure-proxy#747]
Right now, with FPN enabled, I can't view treeherder parsed logs like this one:
https://treeherder.mozilla.org/logviewer.html#/jobs?job_id=273160697&repo=autoland

> NetworkError when attempting to fetch resource.
...and it says to ensure that the URL is reachable (it is). The log URL is https://queue.taskcluster.net/v1/task/Kuu_ajilQe-OLfUpgrFoSA/runs/0/artifacts/public/logs/live_backing.log and it loads just fine if I load it directly.

If I open network devtools while loading the parsed-log UI, then I do indeed see that we receive a 404 response from the request to https://queue.taskcluster.net/v1/task/Kuu_ajilQe-OLfUpgrFoSA/runs/0/artifacts/public/logs/live_backing.log (but again, the page loads fine if I load it directly).

If I turn off FPN, I get the expected result (the parsed log loads just fine).

Just a guess: maybe https://queue.taskcluster.net/ has some per-IP-address rate-limiting (with hard failure to 404 responses), when it's being fetched as a resource on another page? (rather than loaded directly)

**Comment by bakulf** [comment]
@dholbert, Can you provide a necko log?

**Comment by dholbert** [comment]
Unfortunately, I can't reproduce anymore.

**Comment by dholbert** [comment]
I'm hitting this again (at https://treeherder.mozilla.org/logviewer.html#/jobs?job_id=272726453&repo=autoland&lineNumber=2944 ). How do I capture a necko log?

**Comment by dholbert** [comment]
Actually I realized the issue I'm hitting today isn't FPN-related. It seems queue.taskcluster.net just has an overly-restrictive CSP - the "get" fails with a CSP error -- and that happens even in a fresh profile without FPN now:
![image](https://user-images.githubusercontent.com/426803/68616928-e56f0180-047a-11ea-9034-389cdcdde75e.png)

(This is different from my initial post here, where I was getting a 404 response)

**Comment by bakulf** [comment]
This looks like a non-related issue. A 404 is a server-side issue.
I would close this issue. @dholbert , are you OK with it?

**Comment by dholbert** [comment]
Yeah, we can close this.
