### ISSUE TITLE
New OFF image needed for /welcome

### ISSUE THREAD

**Issue by betsymi** [mozilla/secure-proxy#749]
The off state image that appears on /welcome is from a previous version. We adjusted the copy to be more accurate. The proxy does not protect against malware.

This is for V16.

### Old image
![OFF screenshot old](https://user-images.githubusercontent.com/43555492/67971256-75d75780-fbda-11e9-89ac-c90acaf6ab2d.png)

### New image needs to reflect this screen
![image](https://user-images.githubusercontent.com/43555492/67971356-a3240580-fbda-11e9-85a8-afd6b535e7fc.png)

**Comment by pdehaan** [comment]
@bakulf Was this fixed via https://github.com/mozilla/secure-proxy/pull/802/files?short_path=8d8b3f4#diff-8d8b3f4e46bb68fb6a7f4625bd1ec640?

![New_welcome_page_-_issue__797_by_bakulf_·_Pull_Request__802_·_mozilla_secure-proxy](https://user-images.githubusercontent.com/557895/69499515-afcd0e00-0ea7-11ea-994c-9fcced2f4193.png)
