### ISSUE TITLE
FPN says it "encountered an unknown issue" when enabled, with 407 responses from test.factor11.cloudflareclient.com

### ISSUE THREAD

**Issue by dholbert** [mozilla/secure-proxy#756]
Starting today, one of my machines fails to connect to FPN -- it says it "encountered an unkonwn issue. Try turning it off and then on again".  And doing that doesn't help.

When it's switched on and in this "unknown issue" state:
 - every pageload fails (either with "Unable to connect" or "The proxy server is refusing connections")
 - Browser Console shows XHR requests going to test.factor11.cloudflareclient.com, and failing with HTTP status code 407 Proxy Authentication Required in every case.

If I expand the XHR, I see this among the headers:
```
Proxy-Authorization | Bearer undefined
```

On a different machine where things are working correctly (and where these requests produce 200 OK results), I see "Bearer [some long uid value]" instead of "undefined".  So I suspect that missing bearer ID is the problem...

CC @bakulf

**Comment by dholbert** [comment]
I'm using latest Firefox Nightly with FPN version 15 ("last updated November 5" i.e. today)

**Comment by dholbert** [comment]
(Also, I tried restarting Firefox, and that didn't help. Same issue keeps happening 100% reliably.

**Comment by dholbert** [comment]
Update: today, instead of having an "on/off" switch with a broken on state, FPN instead asks me to sign into my Firefox Account (which I had previously signed into with FPN on this machine).

When I obliged, everything went back to normal.

**Comment by bakulf** [comment]
This issue should be fixed in v17.
