### ISSUE TITLE
FPN GeoIP check fails for IP that resolves to Minnesota

### ISSUE THREAD

**Issue by colintheshots** [mozilla/secure-proxy#758]
When I'm attempting to authenticate to the FPN server, I get the following:
`{"status":451,"msg":"Unavailable For Legal Reasons"}` which results in `{state:"authFailedByGeo"}` inside the secure proxy WebExtension. However, this is happening from an IP address that most Geo IP servers resolve to Minnesota. I thought our GeoIP checks were meant to limit to US-only, so this is likely a bug.

![Screenshot_20191107-134045](https://user-images.githubusercontent.com/626405/68421710-602ada80-0164-11ea-9d00-3d49f777349f.png)

**Comment by colintheshots** [comment]
Looks like the issue is using the DEV server with an account that doesn't have a @mozilla.com email address.

**Comment by bakulf** [comment]
Correct. On dev env we allow just mozilla accounts.

**Comment by madalincm** [comment]
Based on the above comment I'm marking this issue as invalid.
