### ISSUE TITLE
Incorrect string for the authentication error displayed in the SP doorhanger

### ISSUE THREAD

**Issue by madalincm** [mozilla/secure-proxy#763]
#### Affected Platforms:
-  Windows 10 (64-bit)
-  Mac 10.14.2

#### Precondition
- Secure proxy is installed

#### Steps to reproduce
1. Click the secure proxy icon to open the doorhanger
2. Click the continue blue button
3. After the authentication window is open, close it
4. Open again the secure proxy doorhanger

#### Expected result
- The error message string displayed is: "Sign in failed To start using Private Network, sign in to your Firefox account or create one."

#### Actual result:
- The error message string displayed is: "Sign in failed. Try again"

#### Notes
SP version used: v16 unsigned version
Screenshot for this issue:
![authIssueMessage](https://user-images.githubusercontent.com/15685441/68871484-2bd79100-0705-11ea-80c2-063c2cceb76e.png)

**Comment by betsymi** [comment]
Thanks @madalincm In this case, did you complete the authentication? Or did you close the panel before it fully authenticated?

**Comment by madalincm** [comment]
I did not complete the authentification, I have closed it before completing the process.

**Comment by betsymi** [comment]
Thanks. In this case, I think we'd need a new string that is somewhat of a hybrid between the expected result and actual result. This assuming that at this stage, we still don't know if the user already has an account or not. 

Sign in failed. To try again, sign in to your Firefox account or create one.
[ Continue ]

**Comment by bakulf** [comment]
Fixed.

**Comment by madalincm** [comment]
Verified using the latest sp build in Win10x64 in FF Nightly
The string was updated:
![image](https://user-images.githubusercontent.com/15685441/69046023-b7e90180-0a00-11ea-862a-601c8bdd47d0.png)
