### ISSUE TITLE
Secure Proxy does not enable the next pass automatically

### ISSUE THREAD

**Issue by bsurd** [mozilla/secure-proxy#764]
#### Affected Platforms:
-  Windows 10 (64-bit)
-  Mac 10.14.2

#### Affected versions:
- unsigned v16 build

#### Steps to reproduce
1. Open the SP doorhanger.
2. Go into settings and enable the "Auto-Start Passes"
3. Wait for the pass to expire.

#### Expected result
- The next pass automatically starts.

#### Actual result:
- The next pass does not start automatically.

#### Notes
If you're at your last pass it remains enabled until you turn SP off.

![1](https://user-images.githubusercontent.com/17178945/68876253-d7381400-070c-11ea-877f-b09108e747c2.gif)

**Comment by bakulf** [comment]
Fixed. The bug was about the captivePortalURL in nightly.

**Comment by bsurd** [comment]
This issue has been verified with the latest build and is no longer reproducible.
