### ISSUE TITLE
Secure Proxy enables the next pass automatically even if the user has turned it off

### ISSUE THREAD

**Issue by bsurd** [mozilla/secure-proxy#768]
#### Affected Platforms:
-  Windows 10 (64-bit)
-  Mac 10.14.2

#### Affected versions:
- unsigned v16 build

#### Steps to reproduce
1. Open the SP doorhanger.
2. Go into settings and enable the "Auto-Start Passes".
3. Turn off SP.
4. Wait for the pass to expire.

#### Expected result
- As SP was turned off, the next pass should not start even if the user has enabled the "Auto-Start Passes" in settings.

#### Actual result:
- The next pass starts automatically when SP was turned off.

![1](https://user-images.githubusercontent.com/17178945/68933691-def3c900-079d-11ea-99f5-8de7e5419694.gif)

**Comment by bakulf** [comment]
Good catch!

**Comment by bsurd** [comment]
This has been verified with the latest v16 build. The issue is no longer reproducible.
