### ISSUE TITLE
Wrong UI displayed when no more passes are available

### ISSUE THREAD

**Issue by bsurd** [mozilla/secure-proxy#769]
#### Affected Platforms:
-  Windows 10 (64-bit)
-  Mac 10.14.2

#### Affected versions:
- unsigned v16 build

#### Precondition:
Have SP installed and all of your passes used.

#### Steps to reproduce
1. Open the SP doorhanger.
2. Observe the UI.

#### Expected result
- The "Looking for a VPN? Join the waitlist" footer is not displayed.

#### Actual result:
- The "Looking for a VPN? Join the waitlist" footer is displayed.

![image](https://user-images.githubusercontent.com/17178945/68934569-93dab580-079f-11ea-90e1-3a23c03a9420.png)

**Comment by bakulf** [comment]
Fixed!

**Comment by bsurd** [comment]
The correct UI is now displayed after no passes remail.
