### ISSUE TITLE
Continue button not correctly aligned in the doorhanger

### ISSUE THREAD

**Issue by madalincm** [mozilla/secure-proxy#772]
#### Affected Platforms:
-  Windows 10 (64-bit)
-  Mac 10.14.2

#### Affected versions:
- unsigned v16 build

#### Precondition:
Have SP installed

#### Steps to reproduce
1. Open the SP doorhanger.
2. Observe the UI.

#### Expected result
- The blue Continue button is displayed as in the first screenshot from the mockup pages: https://mozilla.invisionapp.com/share/P5RW39B4YB8#/screens

#### Actual result:
- The button is displayed directly under the text:
![image](https://user-images.githubusercontent.com/15685441/68947729-d790e780-07be-11ea-89d1-0e57582d5fb2.png)

**Comment by bakulf** [comment]
@brassy- can you please check if this is a valid issue? Thanks

**Comment by brassy-** [comment]
While the implementation shown in the invision would be ideal, I'm ok with the current implementation. 

@bakulf Should we mark this issue as something to work on in the future and definitly blocking? Or you prefer to have a different issue open? I consider an issue like this one a visual enhacement.

**Comment by bakulf** [comment]
We are going to have a completely new UI. This bug can be closed.
