### ISSUE TITLE
The buttons displayed in the doorhanger have rounded corners

### ISSUE THREAD

**Issue by madalincm** [mozilla/secure-proxy#773]
#### Affected Platforms:
-  Windows 10 (64-bit)
-  Mac 10.14.2

#### Affected versions:
- unsigned v16 build

#### Precondition:
Have SP installed

#### Steps to reproduce
1. Open the SP doorhanger.
2. Observe the UI.

#### Expected result
- The blue Continue button does not have rounded buttons

#### Actual result:
- The button has rounded corners

#### Notes
- This is also reproducing with the Join the waitlist button

![image](https://user-images.githubusercontent.com/15685441/68948023-a4028d00-07bf-11ea-8ca9-cf958fd8ac0e.png)

**Comment by bakulf** [comment]
We want the round button :) @brassy- can you update invision?
