### ISSUE TITLE
Infinite connecting to secure server loop on Linux machines

### ISSUE THREAD

**Issue by bsurd** [mozilla/secure-proxy#774]
#### Affected Platforms:
- Linux Ubuntu 19.04 (64-bit)

#### Affected versions:
- unsigned v16 build

#### Steps to reproduce
1. Disconnect from the internet.
2. Open the SP doorhanger.
3. Try to enable SP.

#### Expected result
- An error is displayed.

#### Actual result:
- SP remains blocked in an infinite connection loop.

#### Notes:
This issue only seems to be reproducible on Linux machines and it's reproducing intermittently. When trying to reproduce on Windows or Mac the error was displayed. 

![image](https://user-images.githubusercontent.com/17178945/68948260-2d19c400-07c0-11ea-8319-b2dd21b8cb24.png)

**Comment by bakulf** [comment]
@bsurd Can you provide a secure-proxy log?

**Comment by bsurd** [comment]
I was not able to reproduce this issue anymore on any of the Linux machines I have tried. If there is no internet connection an error was displayed each time. Closing this issue for now as I can't reproduce it anymore.
