### ISSUE TITLE
Disable zooming in SP doorhanger.

### ISSUE THREAD

**Issue by bsurd** [mozilla/secure-proxy#777]
#### Affected Platforms:
- Windows 10 (64-bit)
- Mac 10.14.2
- Linux Ubuntu 19.04 (64-bit)

#### Affected versions:
- unsigned v16 build

#### Steps to reproduce
1. Open the SP doorhanger.
2. Hold Ctrl/Cmd and scroll in the doorhanger.

#### Expected result
- Nothing happens.

#### Actual result:
- The UI changes in size.

![image](https://user-images.githubusercontent.com/17178945/68950203-55a3bd00-07c4-11ea-8baf-5719bc194512.png)

**Comment by bakulf** [comment]
We have decided that this is what we want to keep a good level of accessibility.
At least for v16.
