### ISSUE TITLE
Incorect string inside the button for the georestriction error view

### ISSUE THREAD

**Issue by madalincm** [mozilla/secure-proxy#778]
#### Affected Platforms:
-  Windows 10 (64-bit)
-  Mac 10.14.2

#### Affected versions:
- unsigned v16 build

#### Precondition:
Have SP build with georestriction enabled installed

#### Steps to reproduce
1. Log in into the SP
2. Observe the UI for georestriction error view

#### Expected result
- The blue button contains the Continue string

#### Actual result:
- The blue button contains the Try again string

![image](https://user-images.githubusercontent.com/15685441/68954087-f5b11480-07cb-11ea-908e-76c9b8049248.png)

**Comment by madalincm** [comment]
This issues was logged because we observed a difference between the mockups and the actual results when using the Secure Proxy, however probably the Try Again string makes more sense. 
We just wanted to make sure any difference from the mock-ups is mentioned in an issue and you guys can decide what works best.

**Comment by bakulf** [comment]
@betsymi do we want to have 'try again' or 'continue' here?

**Comment by betsymi** [comment]
Continue, please.

**Comment by bakulf** [comment]
Fixed

**Comment by madalincm** [comment]
Verified using the latest sp build in Win10x64 in FF Nightly
The button was updated. 
![image](https://user-images.githubusercontent.com/15685441/69046852-9d178c80-0a02-11ea-9bf5-b8e20ecdc781.png)
