### ISSUE TITLE
The generic error text is not correct and when it is displayed it causes display issues in the doorhanger

### ISSUE THREAD

**Issue by madalincm** [mozilla/secure-proxy#784]
#### Affected Platforms:
-  Windows 10 (64-bit)
-  Mac 10.14.2

#### Affected versions:
- unsigned v16 build

#### Precondition:
Have SP build installed, the user is logged in

#### Steps to reproduce
1. Disconnect from the internet
2. Open the sp doorhanger 
3. Use the button to turn the SP on

#### Expected result
- The generic error text is: "Your connection was doped. Try turning Firefox Private Network on again." like displayed in the mockups here: https://mozilla.invisionapp.com/share/P5RW39B4YB8#/screens/386774837_secure-Extension-Afterbeta
- Not all the content of the doorhanger is displayed, the user needs to use the scroll bars to see the join the waitlist link 

#### Actual result:
- The generic error text is: Firefox Private Network encountered an unknown issue. Try turning it off, then on again," 
- There are no display issues.

![genericErrorIssue](https://user-images.githubusercontent.com/15685441/69052098-cccc9180-0a0e-11ea-90f9-f8611b16c2b3.jpg)

**Comment by bakulf** [comment]
This text is not valid. @betsymi can you confirm that we only show this message when things go wrong? "Firefox Private Network encountered an unknown issue. Try turning it off, then on again."

**Comment by betsymi** [comment]
If this is a generic error, the actual result is correct. This is because when something is broken and we don't know what it is, we don't assume anymore that there is a problem with the connection.

However, if we do know the issue is a problem with their internet connection, then the error should reflect that and say `You are offline. Check your network connection and try again.`

**Comment by bakulf** [comment]
Better to keep a generic error message.

**Comment by madalincm** [comment]
The problem with the display issue when the warning is displayed has been fixed:
![image](https://user-images.githubusercontent.com/15685441/69238091-cc173500-0b9f-11ea-8c63-3a6a42b70b57.png)
