### ISSUE TITLE
The warning sign displayed in the doorhanger is red

### ISSUE THREAD

**Issue by madalincm** [mozilla/secure-proxy#788]
#### Affected Platforms:
-  Windows 10 (64-bit)
-  Mac 10.14.2

#### Affected versions:
- unsigned v16 build

#### Precondition:
Have SP build installed

#### Steps to reproduce
1. Click the secure proxy icon to open the doorhanger
2. Click the continue blue button
3. After the authentication window is open, close it
4. Open again the secure proxy doorhanger

#### Expected result
- The warning sign is black

#### Actual result:
- The warning sign is red

The issue is reproducing for all the warning messages
![image](https://user-images.githubusercontent.com/15685441/69137088-b84ad080-0ac4-11ea-9a3d-2c4ace4c2f03.png)

**Comment by bakulf** [comment]
Fixed.

**Comment by madalincm** [comment]
Verified as fixed. The warning sign has been updated:
![image](https://user-images.githubusercontent.com/15685441/69238003-96724c00-0b9f-11ea-883c-8ee8010c1c7a.png)
