### ISSUE TITLE
/welcome copy & images need to be updated for V16

### ISSUE THREAD

**Issue by betsymi** [mozilla/secure-proxy#797]
## Welcome to Firefox Private Network 
You can use this lightweight browser extension to enhance your privacy and security on Firefox for Desktop. Use it to:

1. Increase your privacy on public Wi-Fi
2. Mask your browsing history from your internet service provider 
3. Hide your location to reduce online tracking and data collection

### Your privacy
Firefox is committed to your protecting your privacy. The browser-level protection, provided by Cloudflare, temporarily logs unidentified browsing history and deletes this data within 24 hours as a mechanism to detect and handle abuse on the network. Neither Firefox nor Cloudflare is able to associate usage with users as each party holds partial aspects of this data which are never joined.

Firefox doesn’t collect information about your browsing. We do receive your Firefox account registration information and collect generic information about how you use the extension, such as data about how you interact with it, when you turn it off, and technical information about how it functions. Our [privacy policy](https://www.mozilla.org/privacy/firefox-private-network/) describes how we handle this data. You may opt out of sharing this data with us at any time. 

**How to opt out of sending Firefox performance data** 

  1. Click the menu button {menu} and choose Preferences in Mac or Options in PC
  2. Select Privacy & Security on the left
  3. Scroll down to Firefox Data Collection and Use
  4. Uncheck Allow Firefox to send technical and interaction data to Mozilla

### Using Private Network
Look for the Private Network icon in your Firefox toolbar.

[image of Icon in toolbar]

Select the icon and you'll be asked to sign in with a Firefox account. If you don’t already have a Firefox account, you can also create one by clicking Continue.

Once you’re signed in, you'll receive 12 passes a month of Firefox Private Network, each valid for one hour. To claim a pass, simply turn Private Network on. Use Firefox as usual, and your browsing will be encrypted and sent through a proxy service provided by our trusted partner Cloudflare. Passes expire after one hour, even if you turn Private Network off. You’ll receive 12 new passes at the beginning of each month. 

[image of extension panel ON]

When Private Network is off, your Firefox activity will route directly to your Internet connection. It will not be sent through Private Network's service.

[image of extension panel OFF]

### Giving feedback and getting updates 
Because this is a beta test, Private Network will occasionally open a tab in the Firefox browser to give you updates or to ask for your feedback about your experience.

We would love to hear from you at anytime so we can improve the service.

1. Select the Private Network icon from your Firefox toolbar
2. Select the gear icon [gear inline img] to go to Settings
3. Select Leave Feedback

[image of Settings panel with Leave Feedback highlighted]
### Getting help and support
Need help? Here's how to access our support content:

1. Select the Private Network icon from your Firefox toolbar
2. Select the gear icon [gear inline img] to go to Settings
3. Select Help & Support

**Comment by bakulf** [comment]
"Because this is a beta test, Private Network will occasionally open a tab in the Firefox browser to give you updates or to ask for your feedback about your experience."

This is the only place where we say "beta". Is it correct?

**Comment by brassy-** [comment]
![doorhanger-feedback](https://user-images.githubusercontent.com/6309827/69418684-7ff0ff80-0d1b-11ea-8cde-6a9f58a36263.png)
![doorhanger-icon](https://user-images.githubusercontent.com/6309827/69418686-7ff0ff80-0d1b-11ea-9ca3-20f707880755.png)
![doorhanger-off](https://user-images.githubusercontent.com/6309827/69418687-7ff0ff80-0d1b-11ea-95f1-36b2311d73f4.png)
![doorhanger-on](https://user-images.githubusercontent.com/6309827/69418688-80899600-0d1b-11ea-9e55-7c8fbe122a63.png)


@bakulf Do you think we are also able to align the header with the website header?

**Comment by betsymi** [comment]
@bakulf Good point. Let's simply update the headline to: **Welcome to Firefox Private Network Beta**
