### ISSUE TITLE
No "build" script for npm run build in master branch

### ISSUE THREAD

**Issue by sharmaaditya570191** [mozilla/secure-proxy#803]
![image](https://user-images.githubusercontent.com/42587159/69475124-67eab000-0def-11ea-8c1f-c8b2e5591517.png)

**Comment by sharmaaditya570191** [comment]
Hey @bakulf .The package.json does not have a build script in the master branch. I am not able to build SP. Is it necessary to have Firefox Nightly to build it?

**Comment by bakulf** [comment]
Hi @sharmaaditya570191 'npm run build' is not required. Let me update the readme.
'npm install' should be enough to install the dependency.

**Comment by sharmaaditya570191** [comment]
Hi @bakulf . Could you please guide me on how to start contributing to this. I am not able to build it. Is `Firefox Nightly` needed to build this?
