### ISSUE TITLE
"npm start" giving error

### ISSUE THREAD

**Issue by sharmaaditya570191** [mozilla/secure-proxy#806]
![image](https://user-images.githubusercontent.com/42587159/69519290-aca55100-0f7f-11ea-898e-14ad57600984.png)
Getting Error: not found: firefox-nightly. I have Firefox Web Browser. I have also installed nightly in my home folder. Please help me to set up the project so that I can start contributing.
**OS:** Ubuntu 18.04

**Comment by bakulf** [comment]
What I do locally is to set WEB_EXT_FIREFOX. For instance I have this in my .zshrc (you use zsh, right?): `WEB_EXT_FIREFOX=/tmp/firefox/firefox`

Internally `npm start` uses web-ext. To know more about how to configure it, read the official documentation: https://extensionworkshop.com/documentation/develop/getting-started-with-web-ext/#Testing_in_Firefox_for_Android
