### ISSUE TITLE
Incorrect welcome page title

### ISSUE THREAD

**Issue by bsurd** [mozilla/secure-proxy#810]
#### Affected Platforms:
- Windows 10 (64-bit)
- Mac 10.14.2
- Linux Ubuntu 19.04

#### Affected versions:
- unsigned v17 build

#### Steps to reproduce
1. Install SP.
2. Observe the welcome page title.

#### Expected result
- The title should be **Welcome to Firefox Private Network Beta**, as stated by @betsymi in https://github.com/mozilla/secure-proxy/issues/797#issuecomment-557530806

#### Actual result:
- The title is **Welcome to the Firefox Private Network Beta**

**Comment by bsurd** [comment]
Reopening this as when installing v17 the title still reads "Welcome to the Firefox Private Network Beta".

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible using the latest Secure proxy (v18 - unsigned). Verified on the latest Firefox Release (72.0.1), on Windows 10 x64.
