### ISSUE TITLE
Google Doc needs permissions

### ISSUE THREAD

**Issue by Nepaltechguy2** [mozilla/secure-proxy#814]
The last bullet under documentation has a link that redirects to a google doc that requires permission to view. 

Doc in question: https://docs.google.com/document/d/17_-TR4pD6zTy76jm88B1DFE-RNTWPC56yOB0C75XYqk/edit?ts=5ce6d7ad

Solution: Either open it up or create a md file with the same contents in-repo.

**Comment by bsurd** [comment]
Verified with the unsigned v18 version of SP. All links from the current version of the document open without any problems.
