### ISSUE TITLE
Add UTM parameters to the FPN VPN links within the v17+ secure proxy

### ISSUE THREAD

**Issue by chrismore** [mozilla/secure-proxy#821]
We need to append UTM parameters to the to the https://fpn.firefox.con/vpn URL for two unique use cases. 

1) Secure proxy to vpn link -- passes expire upgrade (shown at the bottom before passes expire)

https://fpn.firefox.com/vpn?utm_medium=secure-proxy&utm_source=firefox-browser&utm_campaign=upgrade&utm_content=passes-expired

2) Secure proxy to vpn link -- looking for vpn (shown after passes expire)

https://fpn.firefox.com/vpn?utm_medium=secure-proxy&utm_source=firefox-browser&utm_campaign=upgrade&utm_content=looking-for-vpn

Currently, there are no UTM parameters on the links, so the anonymous web traffic will look like direct traffic from Firefox 71 and we will not be sure if upgrade path is providing any value to users of the secure proxy.

**Comment by chrismore** [comment]
@bakulf @johngruen ^^

**Comment by chrismore** [comment]
@bakulf to confirm that this issue is resolved and the PR is merged, but no new XPI has been pushed out to, right?

**Comment by johngruen** [comment]
that's correct

**Comment by bsurd** [comment]
Verified this with the unsigned v18 build of SP. The UTM parameters have been updated with the new ones.
