### ISSUE TITLE
Copy changes on final screen after user has claimed all 12 passes

### ISSUE THREAD

**Issue by betsymi** [mozilla/secure-proxy#822]
Update messaging on the final screen to read:

You'll receive 12 new passes at the beginning of next month. For unlimited protection, join the waitlist to upgrade to the full-device VPN.

Do we have any wordcount restrictions? This copy is adding three additional words.

**Comment by chrismore** [comment]
r+ we should try to get this change done with issue #821 at the same time.

**Comment by bsurd** [comment]
Verified with the v18 unsigned version. The text has been updated accordingly.
