### ISSUE TITLE
"Free passes left this month: NaN"

### ISSUE THREAD

**Issue by cpeterso** [mozilla/secure-proxy#824]
FPN reported its usual "Firefox Private Network needs your attention" when I woke my sleeping laptop this morning (issue #823), but then it said I had used up all my free passes. The menu said I had `NaN` free passes left this month:

![Free_passes_left_this_month_NaN](https://user-images.githubusercontent.com/629193/71101397-7bc5cf80-216b-11ea-9589-2a4ea5e5fa8a.png)

I don't know if these next part is a bug or not: I disabled and re-enabled the FPN extension and now I can browse with FPN even though I supposedly had no passes remaining. Perhaps the pass expiration code is confused by network errors after waking my laptop, like issue #823?

**Comment by cpeterso** [comment]
Possibly related: I had switched my DoH provider from Cloudflare to NextDNS (`https://trr.dns.nextdns.io/` in Network Settings) the day before. When I woke my sleeping laptop this morning, I was unable to connect to any websites until I reverted back to Cloudflare. That's likely a problem with DoH DNS bootstrap, but perhaps it also confused FPN into thinking I had no more (NaN) passes remaining?

**Comment by cpeterso** [comment]
I reproduced this NaN error again when I was having (different) DoH/DNS problems. Is the UI fetching the number of remaining passes from an account server and then doing math on an undefined result when DoH/DNS problems make the account server unreachable?

**Comment by madalincm** [comment]
We were not able to to reproduce this issue while we were testing the v18 version of Secure Proxy. @cpeterso is this still reproducing for you?

**Comment by cpeterso** [comment]
> We were not able to to reproduce this issue while we were testing the v18 version of Secure Proxy. @cpeterso is this still reproducing for you?

No, though I had to stop using Secure Proxy due to other bugs.
