### ISSUE TITLE
Doorhanger not dismissed when opening a new tab using keyboard shortcut

### ISSUE THREAD

**Issue by madalincm** [mozilla/secure-proxy#830]
#### Affected Platforms:
- Windows 10 x64.
- All Mac.

#### Firefox versions:
- Firefox Release 72.0.1.

#### Prerequisites:
- The Secure Proxy is installed and enabled.

#### Steps to reproduce
1. Click on Secure Proxy to open the doorhanger.
2. Use the keyboard shortcut to open a new tab.

#### Expected result:
- The doorhanger is dismissed.

#### Actual result:
- The doorhanger is not dismissed .

#### Notes:
This also reproducing when using the keyboard shortcuts for closing tabs, switching between tabs.
![doorhangerNotDismised](https://user-images.githubusercontent.com/15685441/72439128-fefc3480-37ae-11ea-9ff6-990289a9eff0.gif)

**Comment by bakulf** [comment]
This is actually a common behavior in firefox. Any other dialog behaves at the same way.
See the hamburger menu.
