### ISSUE TITLE
Secure Proxy disconnects while browsing on webex.com

### ISSUE THREAD

**Issue by madalincm** [mozilla/secure-proxy#832]
#### Affected Platforms:
- Windows 10 x64.

#### Firefox versions:
- Firefox Release 72.0.1.

#### Prerequisites:
- The Secure Proxy is installed and enabled

#### Steps to reproduce
1. Go to webex.com and log in
2. Browse on the site (start a meeting, join a meeting from the browser)

#### Expected result:
Secure proxy remains enabled.

#### Actual result:
Secure proxy disconnects 
![image](https://user-images.githubusercontent.com/15685441/72523655-efd9bd00-3868-11ea-8f7d-ff8681f597ce.png)

#### Notes
This issue is intermittent and it is only reproducing on windows.

**Comment by bakulf** [comment]
Dup of #835
