### ISSUE TITLE
Secure Proxy disconnects while being in jitsi meeting

### ISSUE THREAD

**Issue by madalincm** [mozilla/secure-proxy#833]
#### Affected Platforms:
- Windows 10 x64.

#### Firefox versions:
- Firefox Release 72.0.1.

#### Prerequisites:
- The Secure Proxy is installed and enabled

#### Steps to reproduce
1. Go to https://jitsi.org/
2. Join a meeting and perform different actions (send a youtube video, go through seetings )

#### Expected result:
Secure proxy remains enabled.

#### Actual result:
Secure proxy disconnects 

#### Notes
This issue is intermittent and it is only reproducing on windows and Ubuntu

**Comment by bakulf** [comment]
Dup of #835
