### ISSUE TITLE
Secure Proxy disconnects while browsing on amazon.com

### ISSUE THREAD

**Issue by madalincm** [mozilla/secure-proxy#834]
#### Affected Platforms:
- Windows 10 x64.
- MacOS

#### Firefox versions:
- Firefox Release 72.0.1.

#### Prerequisites:
- The Secure Proxy is installed and enabled

#### Steps to reproduce
1. Go to amazon.com
2. Browse on the site (add products to cart, go to cart etc)

#### Expected result:
Secure proxy remains enabled.

#### Actual result:
Secure proxy disconnects

**Comment by bakulf** [comment]
Dup of #835
