### ISSUE TITLE
Document the conditions that might cause each of the errors we record

### ISSUE THREAD

**Issue by johngruen** [mozilla/secure-proxy#836]
This could be done in a comment in code or in our docs or wherever, but it would be good to put some documentation explaining why we might see each of the six network errors we handle.

https://github.com/mozilla/secure-proxy/blob/master/src/background/network.js#L481-L499

**Comment by bakulf** [comment]
This has been done months ago in the metrics.md: https://github.com/mozilla/secure-proxy/blob/master/docs/metrics.md
