### ISSUE TITLE
add an event category to log upsell engagments

### ISSUE THREAD

**Issue by johngruen** [mozilla/secure-proxy#838]
User story:

As a PM, so that I can reason about user interest in different upsell CTAs i would like a category of telemetry events that tells me what UIs users are interacting with.

So I think we should have  a new event category for this, maybe `upsellEngagment` or something
where objects are assigned uniquely for each different upsell...in the current version, for example we might have `vpnLinkFooter` and `vpnLinkPassesExpired`. Finally, this event should pass in the value that records the version of the extension

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/FPN-22)
┆Issue Number: FPN-22
┆Priority: Low

**Comment by bakulf** [comment]
@johngruen  - So far, in secure-proxy there are VPN 2 links: vpnLinkFooter and vpnLinkPassesExpired. Are you OK to add this event in these 2 locations or you have more places to suggest?

**Comment by johngruen** [comment]
These are fine for now, yes. As long as we can filter on the extension version!
