### ISSUE TITLE
add an event category to expiration of free-tier

### ISSUE THREAD

**Issue by johngruen** [mozilla/secure-proxy#839]
I know we kind of get this from the proxyEnabled event, but i would like a specific additional event fired whenever a user uses up the totality of their free proxy time/data/whatever for the month. We could add this as an event in the `state` method, with an object of `complete` and a value that maps to whatever the free type is...something like `passes, time, data` or whatever.

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/FPN-21)
┆Issue Number: FPN-21
┆Priority: Low

**Comment by data-sync-user** [comment]
➤ John Gruen commented:

We are removing free tier...we don't have to do thi
