### ISSUE TITLE
Investigate why pass tier users are not growing dispite installs.

### ISSUE THREAD

**Issue by johngruen** [mozilla/secure-proxy#840]
We saw 1400 installs last week but only a net growth of 2 DAU for pass based users. Presumably new installs would be pass-based so it would be good to review the code that puts users into the pass vs unlimited cohort in the first place.

See Daily Usage by Client Type Chart [here](https://sql.telemetry.mozilla.org/dashboard/fpn-secure-proxy-tracker-beta-)

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/FPN-20)
┆Issue Number: FPN-20
┆Priority: Low

**Comment by bakulf** [comment]
https://sql.telemetry.mozilla.org/dashboard/fpn---secure-proxy---baku-s-dashboard#171964
I'm working on a better dashboard. I'm planning to write an email explaining what I have found, crunching telemetry data.
