### ISSUE TITLE
Implement survey of unlimited users to prep for migration

### ISSUE THREAD

**Issue by johngruen** [mozilla/secure-proxy#841]
* URL: https://qsurvey.mozilla.com/s3/fpn-fitness-checkup
* Required parameters: Survey sould pass in params per https://github.com/mozilla/secure-proxy/blob/66e88cf64ddc4092e7a4987815e4c0ae9327ab1b/src/background/survey.js#L160
* How it gets deployed: Coming soon.

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/FPN-24)
┆Issue Number: FPN-24
┆Priority: Low

**Comment by bakulf** [comment]
@johngruen No news for that, right?

**Comment by johngruen** [comment]
You can use this URL: https://qsurvey.mozilla.com/s3/fpn-fitness-checkup

please note I don't expect to have the actual survey in place until EOW
