### ISSUE TITLE
cake bring up ring a bell ?

### ISSUE THREAD

**Issue by MarkIIwain** [mozilla/secure-proxy#847]
well ,here without your proxy ,well so far so good .And not even try to update ,because it is not mean helpful .

I felt sick of rather performance like IT tech .I am really not into this course "poser" as a short name .For something late these day keeping me up with ,it would got me nothing capable .You know just following the line ,I am running on my fashion-out DT ,little disk space ,and trying a play in GitHub repo on linux something .And I am using windows huh .These thing keep me satisfied once on linux gone far away .The fact is firefox ate up my disk space ,to show it useful it brought into greater in deal with .

I will not buy anything more sophisticated than google packages even bother backsmali it .Actually I want is version-select from "stored" history xpi for example which mozilla denied to offer .You know it more like scheme ,it would change not the fact leads .If a version is possible to acquire ,for what make such difference between a VPN or proxy do ?People actually shall think over to give it up .

It is not a play ,and I am not qualified commentary .It is not rock n' roll thing ,since there half of packed with build instruct take cp instead of copy ,which the command shall not taken by windows console ,and other packed may just ignored the build phrase that lead another error sent back by npm .Am I really enjoying doing research in this thing ?

It is shall be a cake so bring it on .I know I can get the treat somewhere .

**Comment by bakulf** [comment]
I don't understand what this bug is about. Can you file it again? Thanks.
