### ISSUE TITLE
when activated, secury-proxy bypasses hosts file

### ISSUE THREAD

**Issue by evelyn-marie** [mozilla/secure-proxy#850]
Submitted on behalf of a SUMO user:

> Both Firefox Private Network and Firefox DNS-over-HTTPS with cloudflare is bypassing the hosts file. All the address I block in the hosts file is getting through if I enable Private Network or DNS-over-HTTPS 

https://support.mozilla.org/en-US/questions/1279630

**Comment by bakulf** [comment]
this is a platform bug. See https://bugzilla.mozilla.org/show_bug.cgi?id=1616252
