### ISSUE TITLE
Turn off network.trr.fetch_off_main_thread

### ISSUE THREAD

**Issue by KershawChang** [mozilla/secure-proxy#856]
See bug 1620824 [1].
TRR is not working properly with FPN extension when network.trr.fetch_off_main_thread is enabled.
We want to turn off network.trr.fetch_off_main_thread by FPN extension.

[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1620824

**Comment by bakulf** [comment]
If this is something that happens only in nightly, we can wait until the issue is fixed and uplift it to beta, if needed.

**Comment by KershawChang** [comment]
It's not easy to fix this in TRRServiceChannel, since the channel runs completely off main thread and doesn't send "http-on-*" notification. FPN extension has no way to add "Proxy-Authorization" header to the channel. In addition, we'd like to ship TRRServiceChannel in 75, so turning off "network.trr.fetch_off_main_thread" might be the best workaround for now.
