### ISSUE TITLE
Unable to sign into Private Network Extension

### ISSUE THREAD

**Issue by Mcmeman** [mozilla/secure-proxy#861]
Have been unable to sign into the Private Network Extension both on Windows and Mac OS for several days now. Attempts to log in present only the error "sign in failed, to try again sign into your firefox account or create one"

Firefox version 74.0 and Extension version 20

**Comment by jmanc** [comment]
Exact same problem, FF ver. 74.  I changed my password recently, could this be the issue?  I am able to log into firefox just fine, not the priv network

**Comment by Mcmeman** [comment]
> Exact same problem, FF ver. 74. I changed my password recently, could this be the issue? I am able to log into firefox just fine, not the priv network

I don't think so, my PW has not been changed and this seems to be happening to almost everyone.

**Comment by Fanolian** [comment]
I think it may be an Firefox account issue.
My main Firefox account has unlimited access to FPN and cannot log in to it. I set up a brand new Firefox account just for testing FPN and it works, but it changes to the pass-based system.

**Comment by bakulf** [comment]
Do you receive authentication failure or you are unable to use the proxy? Can you describe the single steps? I want to reproduce the issue. Thanks.

@Mcmeman @jmanc @Fanolian

**Comment by Mcmeman** [comment]
> Do you receive authentication failure or you are unable to use the proxy? Can you describe the single steps? I want to reproduce the issue. Thanks.
> 
> @Mcmeman @jmanc @Fanolian

The steps are as follows
-Click on extension in the browser toolbar
-Click "continue" to sign in
-This opens a Firefox sign in window with my account already present and a option to "Sign in"
-Select Sign in and the window closes
- The toolbar extension then flashes a yellow error "Firefox Private Network Needs your attention"
-The extension also has a yellow exclamation point on the icon
-Clicking the extension states "Sign in failed, to try again , sign into your Firefox account or create one"
-Clicking Continue will repeat the process indefinitely.

**Comment by jmanc** [comment]
I, too, am following the precise steps outlined by @Mcmeman.  I have tried this on 3 different computers, all with FF 74.

**Comment by bakulf** [comment]
Thank you all. I would like to know: are you perhaps use the same firefox account on multiple devices? If yes, on how many devices do you have/had secure-proxy active?

@Mcmeman @jmanc @Fanolian

**Comment by Fanolian** [comment]
I used my Firefox Account for FPN to test [bug 1619822](https://bugzilla.mozilla.org/show_bug.cgi?id=1619822) and [bug 1620824](https://bugzilla.mozilla.org/show_bug.cgi?id=1620824) with Mozregression. That means I had to use my same (testing) Firefox profile and FPN login session(?) repeatedly in different Nightly builds (to find the regression regarding FPN).

When testing bug 1620824, I did opened a couple of Firefox profiles and different versions of FPN. I think I used about 6 or 7 different profiles and logged in 10+ times in 3 different FPN versions (v15, 19, 20).

All logins were performed on the same computer, but I had ProtonVPN enabled so I might have switched the connected server regions a few times between logins.

I cannot remember the exact date, but I think my account started stopping from signing in FPN since Mar 9 to Mar 12.

**Comment by Mcmeman** [comment]
Yes I use my FF account on several devices. As for the Desktop Extension I
have it enabled on 1 windows 10 machine and 1 Mac OS machine.

**Comment by jmanc** [comment]
I also use it on 3 different computers, all Linux with FF74.

**Comment by bakulf** [comment]
The issue is fixed. Try to login again and sorry!

**Comment by Mcmeman** [comment]
This issue appears to have resurfaced after the most recent update to Firefox.

**Comment by rlr** [comment]
@Mcmeman can you confirm that it's fixed now? We just deployed a fix. Thanks!

**Comment by Mcmeman** [comment]
Yep it works now, if I may ask what is causing that specific issue?

**Comment by rlr** [comment]
> Yep it works now, if I may ask what is causing that specific issue?

This latest issue was a bad database migration we ran on the database.

**Comment by Mcmeman** [comment]
Thanks for letting me know.

**Comment by jmanc** [comment]
Works for me, too.  Thank you!
