### ISSUE TITLE
Unable to log in due to HTTP 500 Internal Server Error

### ISSUE THREAD

**Issue by Fanolian** [mozilla/secure-proxy#864]
When I try to use a pass, _Browser Console_ shows
`XHR  POST  https://fpn.firefox.com/browser/oauth/token
[HTTP/2 500 Internal Server Error 5713ms]`

I think the issue started around 12 hours ago.

**Comment by rlr** [comment]
@Fanolian can you confirm that it's fixed now? We just deployed a fix. Please reopen if it still happens. Thanks!

**Comment by Fanolian** [comment]
Fixed. Thanks!
