### ISSUE TITLE
“Settings” link from Secure Proxy onboarding window does not work when the internet is off

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/secure-proxy#888]
#### Affected versions:
- All Firefox;

#### Affected FxA versions:
- 1.172.0;

#### Affected Platforms:
- Windows 10 (64-bit);

#### Preconditions
- have the Secure Proxy v22 (intermediate message version) extension installed and active;

#### Steps to reproduce
1. Click on the SP icon from the toolbar and observe that the extension is active.
2. Turn off the internet connection
3. Click on the SP icon from the toolbar again (an error message should be displayed)
4. Click on the “Settings” link from inside the onboarding window

#### Expected result:
User is redirected to the Settings menu.

#### Actual result:
Nothing happens.

#### Notes:
- Not reproducing for the Secure Proxy live version.
- Not reproducing if the internet error message is not displayed.
- Clicking on the Settings - wheel icon works as expected.
![s](https://user-images.githubusercontent.com/15685960/82895641-2af9a480-9f5d-11ea-9c76-f6195e76034b.png)

**Comment by bakulf** [comment]
The fix is trivial but v22 is a temporary release. Let's see if we want to ship a new version for this fix.
