### ISSUE TITLE
Previously disabled Secure Proxy does not trigger the survey at remove

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/secure-proxy#889]
#### Affected versions:
- All Firefox;

#### Affected FxA versions:
- 1.172.0;

#### Affected Platforms:
- Windows 10 (64-bit);

#### Preconditions:
 - have the Secure Proxy v.23 extension installed

#### Steps to reproduce
1. Go to about:addons and disable the SP extension.
2. From the same page, remove the extension after disabling it.

#### Expected result:
- A survey is triggered at extension remove.

#### Actual result:
- The survey is not triggered at extension remove.

#### Notes:
- Reproducing for the intermediate “message” version, also.
![survey](https://user-images.githubusercontent.com/15685960/83252105-58d82680-a1b3-11ea-88a4-2760269e128f.gif)

**Comment by mixedpuppy** [comment]
A disabled extension being removed should never trigger anything.  If that is the expectation, it should be done when getting disabled.

**Comment by bakulf** [comment]
This is the expected behavior. Thanks @mixedpuppy !
