### ISSUE TITLE
Any testing account has unlimited access to Secure Proxy even if no subscription was made

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/secure-proxy#890]
#### Affected versions:
- All Firefox;

#### Affected FxA versions:
- 1.172.0;

#### Affected Platforms:
- Windows 10 (64-bit);

#### Preconditions:
 - have the Secure Proxy v.23 extension installed

#### Steps to reproduce
1. Sign up to SP using a test email (not Mozilla).
2. Finalize log in.
3. Click “Continue” in the onboarding panel to finalize SP activation.

 #### Expected result:
- A subscription message is displayed in the onboarding panel. The SP is not active yet.

#### Actual result:
- No subscription message is displayed and the SP is active and unlimited for the logged user.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2010)
┆Issue Number: FXA-2010

**Comment by bakulf** [comment]
This should be fixed now. The staging env did not have the subscription check enabled.

**Comment by ValentinaPC** [comment]
Verified as fixed in stage, using Fx79 and Windows 10 (64-bit).
While using a non Mozilla/SV account, user is asked for subscription.
Postfix screenshot below.
![image](https://user-images.githubusercontent.com/15685960/84984881-6181a400-b144-11ea-9ab6-1aafe8a86d2b.png)
