### ISSUE TITLE
Subscription Proxy "Loading..." doorhanger has layout issues

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/secure-proxy#898]
#### Affected versions:
- All Firefox;

#### Affected FxA versions:
- 1.175.0;

#### Affected Platforms:
- Windows 10 (64-bit);

#### Preconditions
- Have the latest Subscription Proxy (that points to FxA stage) installed;

### Steps to reproduce
1. Click on the SP icon from the toolbar.
2. Observe the “Loading…” doorhanger.

#### Expected result:
- There are no display or layout issues.

#### Actual result:
- The Firefox Private Network logo is cut.

![image](https://user-images.githubusercontent.com/15685960/84748028-c14f4200-afc0-11ea-9c51-37bda57f9316.png)

**Comment by johngruen** [comment]
oops!

**Comment by ValentinaPC** [comment]
Verified as fixed in stage, using SP v.23 (lates) on Fx77 and Windows 10 (64-bit).
Postfix screenshot below.

![image](https://user-images.githubusercontent.com/15685960/85282427-602ddf80-b494-11ea-9ffd-4c0b78ea9ddb.png)
