### ISSUE TITLE
“Settings” menu accessed from Subscription Proxy “Loading...” screen cannot be exit

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/secure-proxy#904]
#### Affected versions:
- All Firefox;

#### Affected FxA versions:
- 1.176.0;

#### Affected Platforms:
- Windows 10 (64-bit);

#### Prerequisites:
- Have the latest version of the SP installed;
- Use a mailinator account;
(The simplest way to reproduce this is to use the SP Management extension and trigger the “Loading…” door-hanger)

#### Steps to reproduce
1. Load  the profile from prerequisites;
2. Click on the SP icon from toolbar (the "Loading..." door-hanger should be displayed);
3. Click on the “Settings” wheel icon;
4. Click on the back “<” arrow from “Settings” menu;
5. Observe the door-hanger content;

#### Expected result:
- User is redirected to the SP activation door-hanger.

#### Actual result:
- User is still in the Settings menu.

#### Notes:
- User cannot exit Settings menu.
![loading-settings](https://user-images.githubusercontent.com/15685960/85390817-04299080-b552-11ea-8c12-7e1d26b96c29.gif)

**Comment by bakulf** [comment]
#905

**Comment by ValentinaPC** [comment]
Verified as fixed using the latest version of the Subscription Proxy, on Firefox Nightly and Windows 10 (64-bit).
Postfix screenshot below.
![image](https://user-images.githubusercontent.com/15685960/85731830-84432800-b703-11ea-834a-38efad48f59c.png)
