### ISSUE TITLE
Unable to log into Firefox private network

### ISSUE THREAD

**Issue by mrkannan3** [mozilla/secure-proxy#907]
[log.txt-main.18544.log](https://github.com/mozilla/secure-proxy/files/4854851/log.txt-main.18544.log)

log file is attached.

**Comment by johngruen** [comment]
Hi @mrkannan3 we believe this was an issue with teh firefox accounts system that provides authentication for the proxy and that this issue is now resolved. Are you able to log in now?

**Comment by mrkannan3** [comment]
Yes. It works now. Thanks
